import unittest
from collections import Counter

from similarity.TextUtils import jaccard_counter_similarity, singleword_similarity, desc_overlap_url
from similarity.UclassifyUtils import uclassify_topics, uclassify_similarity


class TextUtilsTests(unittest.TestCase):
    pinterest_profile = {'username': 'deathjazz69',
                         'about': '',
                         'domain_url': None,
                         'following_count': 5,
                         'image_xlarge_url': 'https://i.pinimg.com/280x280_RS/6b/71/20/6b7120f396928249c8e50953e64d81f5.jpg',
                         'locale': 'ja',
                         'country': 'JP',
                         'noindex_reason': '',
                         'indexed': True,
                         'location': '',
                         'full_name': '次 夢',
                         'follower_count': 58,
                         'domain_verified': False,
                         'pin_count': 1702,
                         'board_count': 8,
                         'image': 'https://i.pinimg.com/280x280_RS/6b/71/20/6b7120f396928249c8e50953e64d81f5.jpg'
                         }
    flickr_profile = {'image': 'https://live.staticflickr.com/4347/buddyicons/158917054@N04_r.jpg',
                      'screen_name': 'sakuranyo chan'}
    twitter_profile = {"image": "https://pbs.twimg.com/profile_images/578507474606522368/0dS0jREn_400x400.jpeg",
                       "url": "stickerlabel.com.au",
                       "description": "Owner of Sticker Label Shop, Passionate about using technology to improve business processes; BSc Comp Sci",
                       "name": "Johnny Lam", "username": "@7ohnn1", "location": "Sydney , Singapore"}
    instagram_profile = {
        'image': 'https://instagram.fcbr1-1.fna.fbcdn.net/vp/87883f991eebecd27ea361444d9921ca/5E0FB5DE/t51.2885-19/s150x150/21435772_523568091343574_7555943046806765568_a.jpg?_nc_ht=instagram.fcbr1-1.fna.fbcdn.net',
        'username': '2559_244269_ally_bigboy', 'description': 'Ally Iddy Abdallah Bgboy;;#allyiddyabdalllah@gmail.com'}

    def test_jaccard_counter_similarity(self):
        counter1 = Counter(
            {'gharobar': 109, 'madeinindia': 57, 'smallbusinessesgobig': 56, 'Gharobar': 44, 'punetimes': 38,
             'puneinstagrammers': 28, 'fashionista': 23, 'jewellery': 22, 'puneinsta': 21, 'juttis': 18, 'fashion': 17,
             'sale': 16, 'pune': 15, 'HomeBasedSellers': 15, 'multibrand': 15, 'retailstore': 15, 'shopaholic': 15,
             'fridayfunday': 15, 'onsale': 14, 'kids': 13, 'KnowTheBrand': 13, 'bags': 13, 'salealert': 12,
             'KnowTheSeller': 12, 'startup': 11, 'homemade': 11, 'MakeInIndia': 11, 'EmpoweringEntrepreneurs': 11,
             'entrepreneur': 11, 'raeezjuttis': 10, 'clearancesale': 10, 'love': 9, 'lowestpriceever': 9,
             'homedecor': 9, 'handicrafts': 9, 'giftingideas': 9, 'ootd': 8, 'punefashion': 8, 'summersale': 8,
             'gharobarflea': 8, 'Shofiesm': 7, 'contestAnnouncement': 7, 'shoefiesm': 7, 'saris': 7, 'weddingseason': 7,
             'clothing': 7, 'white': 7, 'juttiswag': 7, 'Pune': 7, 'retailtherapy': 7, 'business': 7,
             'smallbusiness': 7, 'startups': 6, 'German': 6, 'Silver': 6, 'ChennaiFloods': 6, 'unique': 6,
             'designer': 6, 'shop': 6, 'smallbusinesses': 6, 'lifestyle': 6, 'thestylestorybyraeez': 6,
             'mondayvibes': 6, 'leather': 6, 'christopolo': 6, 'beauty': 6, 'fleamarket': 6, 'celebritystyle': 6,
             'madeInIndia': 6, 'necklace': 6, 'traditional': 5, 'design': 5, 'food': 5, 'Raeez_juttis': 5,
             'sundayshopping': 5, 'ethnicjewellery': 5, 'jewelry': 5, 'kurtis': 5, 'handcrafted': 5,
             'CustomerIsKing': 5, 'HomeBasedSeller': 5, 'TGIF': 5, 'silverjewellery': 5, 'skincare': 5,
             'sunflowercreations': 5, 'ethnic': 5, 'leatherbags': 5, 'pamperyourfeet': 5, 'bagswag': 5,
             'ValentinesDay': 5, 'shoppingaddict': 5, 'India': 5, 'Christopolo': 5, 'Adimaa': 5, 'sarinotsorry': 5,
             'beattheheat': 5, 'kitchen': 5, 'Entrepreneur': 5, 'designersaris': 5, 'makeup': 4, 'quoteoftheday': 4,
             'handmade': 4, 'amulyamjewels': 4, 'handbags': 4, 'summerfashion': 4, 'Pearl': 4, 'colours': 4, 'baby': 4,
             'MadeInIndia': 4, 'india': 4, 'upto50': 4, 'amazingoffers': 4, 'juttilove': 4, 'indiheart': 4,
             'kidsfashion': 4, 'wedding': 4, 'footwear': 4, 'Kutch': 4, 'motivation': 4, 'HomeBasedBusiness': 4,
             'red': 4, 'punjabijutti': 4, 'aesthetic': 4, 'shopping': 4, 'watches': 4, 'famousquotes': 4, 'sari': 4,
             'sariswag': 4, 'wallets': 4, 'anniversarygift': 4, 'earrings': 4, 'comfortable': 4, 'gifts': 4,
             'indianjewellery': 4, 'inspiration': 4, 'newyear': 4, 'Hustle': 4, 'WednesdayWisdom': 4, 'thejewelbox': 4,
             'eidsale': 4, 'life': 4, 'digitalmarketing': 4, 'businessowner': 4, 'MondayBlues': 4, 'Jhumka': 3,
             'western': 3, 'colour': 3, 'homebusiness': 3, 'ChennaiRainsHelp': 3, 'repost': 3, '99Store': 3,
             'stylish': 3, 'differentcolours': 3, 'designerjewellery': 3, 'indian': 3, 'royal': 3, 'Earrings': 3,
             'weddingSeason': 3, 'multibrandstore': 3, 'elegant': 3, 'homebasedsellers': 3, 'ValentinesWeekSale': 3,
             'slingbag': 3, 'tuesdayvibes': 3, 'festivalseason': 3, 'handicraftsofindia': 3, 'products': 3,
             'christmasgifts': 3, 'newarrivals': 3, 'Mumbai': 3, 'dress': 3, 'Christmas': 3, 'entrepreneurlife': 3,
             'entrepreneurship': 3, 'success': 3, 'beautiful': 3, 'discounts': 3, 'weddingjewellery': 3, 'colourful': 3,
             'glittering': 3, 'golden': 3, 'clutch': 3, 'Facebook': 3, 'Ecommerce': 3, 'stones': 3, 'summer': 3,
             'comfort': 3, 'ilovebags': 3, 'perfumes': 3, 'mensfashion': 3, 'Bamboo': 3, 'raeez': 3, 'cottonsaris': 3,
             'chic': 3, 'pretty': 3, 'bracelet': 3, 'retailer': 3, 'westendmall': 3, 'trendy': 3, 'chocolates': 3,
             'accessories': 3, 'Avadh': 3, 'kamakshistudio': 3, 'passion': 3, 'leatherbelts': 3, 'Instagram': 3,
             'weddingfashion': 3, 'sunglasses': 3, 'quotes': 3, 'nofilter': 3, 'amazing': 3,
             'EmpoweringHomeBasedSellers': 3, 'ethnicwear': 3, 'businesstips': 3, 'exclusive': 3, 'designerwear': 3,
             'bedsheets': 3, 'Festival': 3, 'dufflebags': 3, 'ThursdayThoughts': 2, 'well': 2, 'wear': 2, 'foodie': 2,
             'happyshopping': 2, 'happyfriendshipday': 2, 'thursdayvibes': 2, 'differentdesigns': 2,
             'DressLikeAnIndianWoman': 2, 'silver': 2, 'gold': 2, 'newArrivals': 2, 'kurtapalazzosets': 2,
             'homemadefood': 2, 'summeressentials': 2, 'sunprotection': 2, 'Feel': 2, 'queen': 2, 'Button': 2,
             'black': 2, 'clothes': 2, 'monsoonsale': 2, 'KidsFashion': 2, 'last2days': 2, 'freedomsale': 2,
             'independenceday': 2, 'supersale': 2, 'lowestprice': 2, 'shoptillyoudrop': 2, 'under99': 2,
             'haldikumkum': 2, 'beautifuldesign': 2, 'semipreciousstones': 2, 'events': 2, 'knowyoursellers': 2,
             'homebasedseller': 2, 'meetyoursellers': 2, 'DIY': 2, 'WinterIsComing': 2, 'celebrate': 2,
             'internationalfamiliesday': 2, 'family': 2, 'marketingstrategy': 2, 'marketingtips': 2, 'ecommerce': 2,
             'kutchibags': 2, 'mirrorwork': 2, 'lucknowichikankari': 2, 'ladyinred': 2, 'chickenkarisuits': 2,
             'anarkalidress': 2, 'prideoflucknow': 2, 'exclusivechickenkari': 2, 'celebrations': 2, 'tuesdaytreat': 2,
             'partyfrocks': 2, 'theadorables': 2, 'prettyfrocks': 2, 'fashionkids': 2, 'childrenswear': 2,
             'fashionbaby': 2, 'childrenfashion': 2, 'specialoccasion': 2, 'WomenEmpowerment': 2, 'socialwork': 2,
             'feminism': 2, 'motd': 2, 'RepublicDay': 2, 'DeshKeSaath': 2, 'kidsFashion': 2, 'Kisha': 2,
             'thursdaytrends': 2, 'shopfromsmallbusiness': 2, 'womensfashion': 2, 'announcement': 2, 'Gujarat': 2,
             'kutchijackets': 2, 'motivationalquotes': 2, 'onlinebusiness': 2, 'interiordesign': 2, 'homesweethome': 2,
             'slipons': 2, 'handblockprint': 2, 'iloveshopping': 2, 'crossby': 2, 'gharobarfleamarket': 2,
             'dailywearearrings': 2, 'now': 2, 'chemicalfree': 2, 'popupsale': 2, 'flat20': 2, 'bagshopping': 2,
             'EmpoweringEntrepreneur': 2, 'royallook': 2, 'chokar': 2, 'flower': 2, 'homemadecrafts': 2,
             'shoppingbonanza': 2, 'craftsmen': 2, 'avadh': 2, 'customisedbags': 2, 'indianfashion': 2, 'firsttime': 2,
             'empoweringWomenInBusinesses': 2, 'bagaddict': 2, 'saree': 2, 'time': 2, 'puneblogger': 2, 'unisex': 2,
             'onlineshopping': 2, 'belts': 2, 'Pongal': 2, 'ring': 2, 'statementring': 2, 'ringswag': 2,
             'jewelryaddict': 2, 'MumbaiRains': 2, 'exquisite': 2, 'pearl': 2, 'festivalfashion': 2, 'Necklace': 2,
             'Red': 2, 'heartshaped': 2, 'fashionistas': 2, 'homeandaway': 2, 'raeez_juttis': 2, 'eidshopping': 2,
             'vegan': 2, 'PMKVY': 2, 'MSDE': 2, 'bronze': 2, 'necklaces': 2, 'ExclusiveJewellery': 2, 'winters': 2,
             'friendshipday': 2, 'pocketfriendly': 2, 'cutegifts': 2, 'zariwork': 2, 'Narrate': 2, 'fairytale': 2,
             'story': 2, 'dressed': 2, 'ultimate': 2, 'cutwork': 2, 'lace': 2, 'tussel': 2, 'glammedup': 2,
             'sarisunday': 2, 'sundaysensation': 2, 'quotestoliveby': 2, 'goals': 2, 'happydance': 2,
             'empoweringWomeninBusinesses': 2, 'HarryPotter': 2, 'nopreservatives': 2, 'day1': 2, 'mothersday': 2,
             'rings': 2, 'help': 2, '5blade': 2, 'scissor': 2, 'swadesh': 2, 'laptopbags': 2,
             'homebasedentreprenuer': 2, 'winter': 2, 'ValentinesIsCompleteIf': 2, 'Raeez': 2, 'quirkygifts': 2,
             'TipTuesday': 2, 'PopUpShow': 2, 'KnowThe': 2, 'genuineleather': 2, 'men': 2, 'motiwork': 2,
             'gotapattiwork': 2, 'highgoldjewellery': 2, 'ChristmasAndChill': 2, 'GiftingIdeas': 2, 'DesignerWear': 2,
             'handmadeWithLove': 2, 'shayonaCrafts': 2, 'decorative': 2, 'Shop': 2, 'handbag': 2,
             'statementjewellery': 2, 'wednesdayvibes': 2, 'quote': 2, 'comment': 2, 'comments': 2, 'TFLers': 2,
             'tweegram': 2, 'song': 2, 'funny': 2, 'photooftheday': 2, 'tbt': 2, 'true': 2, 'word': 2,
             'DigitalIndia': 2, '3D': 2, 'stickers': 2, 'decorate': 2, 'scrapbook': 2, 'planner': 2, 'craftwork': 2,
             'inspirationalquotes': 2, 'onlinemarketing': 2, 'businesswoman': 2, 'kidswear': 2, 'Jewelry': 2,
             'Chritstmastime': 2, 'redtunic': 2, 'blackscarf': 2, 'partydress': 2, 'ghaorbar': 2, 'free': 2,
             'organised': 2, 'SpiceRack': 2, 'shimmerbag': 2, 'partyslings': 2, 'mehndiRasam': 2, 'silksaris': 2,
             'unstitchedclothing': 2, 'glimpses': 2, 'stoles': 2, 'summerswag': 2, 'summerVacations': 2,
             'IndianSummers': 2, 'travelEssentials': 2, 'whatwomenwant': 2, 'rakshabandhan': 2,
             'socialmediamarketing': 2, 'supportsmallbusiness': 2, 'saturdaystyle': 2, 'weddingshopping': 2, 'blog': 2,
             'Wood': 2, 'Kashmir': 1, 'WinterOfficiallyBeginsSo': 1, 'FirstDayOfWinter': 1, 'empoweringentreprenurs': 1,
             'entreprenurship': 1, 'homebasedbusiness': 1, 'inspirational': 1, 'makeithappen': 1, 'prettyooking': 1,
             'lovelylook': 1, 'StartupIndia': 1, 'chennairain': 1, 'abvatandabeyegabutton': 1, 'vote': 1, 'buy': 1,
             'smile': 1, 'uncommon': 1, 'stationery': 1, 'designs': 1, 'use': 1, 'clean': 1, 'floralprints': 1,
             'freesize': 1, 'personalcoaching': 1, 'counseling': 1, 'newlife': 1, 'depression': 1, 'mentalhealth': 1,
             'MindBodySpirit': 1, 'beapartofarevolution': 1, 'oxidisedjewellery': 1, 'statementjewelry': 1,
             'intricatedesigns': 1, 'trendsetterthursdays': 1, 'hygienic': 1, 'bpafree': 1, 'shape': 1,
             'happyEaster': 1, 'salwarSuits': 1, 'exoticjewellery': 1, 'statementnecklace': 1, 'feelroyal': 1,
             'statementpiece': 1, 'grace': 1, 'Jewellery': 1, 'AmericanDiamond': 1, 'ParsiNewYear': 1,
             'FollowFriday': 1, 'FashionWatch': 1, 'accessory': 1, 'pulabazaar': 1, 'exhibitionAlert': 1,
             'socialmedia': 1, 'jewellerylovers': 1, 'newcollection': 1, 'Indian': 1, 'casual': 1, 'semi': 1,
             'exclusivecollection': 1, 'shortkurtis': 1, 'croptop': 1, 'PowerUp': 1, 'martech': 1, 'ports': 1,
             'LoveGetsBetterWithEveryTurn': 1, 'caps': 1, 'hats': 1, 'stars': 1, 'pubglover': 1, 'rfcap': 1,
             'coolcaps': 1, 'theasorables': 1, 'Wear': 1, 'tuesdayshoppingtips': 1, 'forBoys': 1, 'pureCotton': 1,
             'retail': 1, 'MustHavesInYourWardrobes': 1, 'longKaftans': 1, 'originalKashmiriProducts': 1,
             'comfortablefootwear': 1, 'footfetish': 1, 'juttilover': 1, 'imitationjewellery': 1, 'flat10': 1,
             'jutties': 1, 'weekend': 1, 'happynavroz': 1, 'celebrating': 1, 'parsinewyear': 1, 'CustomerOriented': 1,
             'StartYourOwnBusiness': 1, 'FridayReads': 1, 'internationalmarathon': 1, 'Sunday': 1, '2015': 1,
             'eventalert': 1, 'donotmiss': 1, 'show': 1, 'Ensemble': 1, 'returngifts': 1, 'adjustable': 1,
             'Kamakshi': 1, 'simple': 1, 'motheeofpearl': 1, 'keralasarees': 1, 'mundu': 1, 'pattupavada': 1,
             'IndianStartupData': 1, 'lips': 1, 'masher': 1, 'grater': 1, 'squeezer': 1, 'cutter': 1,
             'Japanesetechnology': 1, 'HandMadeWithLove': 1, 'RaeezJutties': 1, 'TheBigJuttieSale': 1,
             'HandmadeBeauties': 1, 'SmallBiz': 1, 'consumers': 1, 'Corporate': 1, 'CorporateGifts': 1, 'Homebase': 1,
             'PuneConnect': 1, 'biotech': 1, 'KutchiHandicrafts': 1, 'happymothersday': 1, 'vibrantkutch': 1,
             'kutchi': 1, 'ajrakhprints': 1, 'botd': 1, 'trendytuesdays': 1, 'celebratingindia': 1, 'oneroof': 1,
             'homebased': 1, 'kind': 1, 'sells': 1, 'festive': 1, 'fashionfair': 1, 'baglady': 1, 'warlidesign': 1,
             'handpainted': 1, 'ChocolatesDay': 1, 'HomemadeValentine': 1, 'kidsootd': 1, 'quilt': 1, 'chand': 1,
             'Bali': 1, 'miss': 1, 'nautanki': 1, 'beautyeditor': 1, 'Traditionalist': 1, 'IndiaSharesIndiaCares': 1,
             'cozyWinters': 1, 'HoodedJacket': 1, 'polkaDots': 1, 'HealthyLiving': 1, 'palazzosets': 1,
             'trendsetters': 1, 'stylewear': 1, 'theJewelBox': 1, 'DivaMrsWestIndia': 1, 'OddEven': 1, 'Pollution': 1,
             'MerryChristmas': 1, 'HomeForChristmas': 1, 'shoplocal': 1, 'Recipe': 1, 'Gandhi150': 1,
             'GandhiJayanti': 1, 'entrepreneurs': 1, 'entrepreneurlifestyle': 1, 'entrepreneurmindset': 1,
             'successquotes': 1, 'iloveshoes': 1, 'comfortshoes': 1, 'shoesaddict': 1, 'shoesforsale': 1,
             'shoestyle': 1, 'shoesshoesshoes': 1, 'Cotton': 1, 'Dress': 1, 'Material': 1, 'Warli': 1, 'dupatta': 1,
             'mondayrules': 1, 'stayclassy': 1, 'semiformalwear': 1, 'indianethnicwear': 1, 'cottonclothing': 1,
             'crossbodybag': 1, 'messengerbag': 1, 'traveller': 1, 'happyAkshayatritiya': 1, 'auspiciousOccassion': 1,
             '18caratgold': 1, 'persistentsystems': 1, 'employeeengagement': 1, 'happyshoppingday': 1, 'happyfriday': 1,
             'pure': 1, 'silverearrings': 1, 'gemstones': 1, 'customise': 1, 'stone': 1, 'microfashion': 1,
             'flamboyant': 1, 'radiates': 1, 'enchanting': 1, 'coloursofjoy': 1, 'TamilNaduRains': 1,
             'PrayForChennai': 1, 'empoweringwomeninbusinesses': 1, 'magnificent': 1, 'sheen': 1, 'entice': 1, 'woo': 1,
             'FridayFashiontips': 1, 'potlibags': 1, 'modern': 1, 'hazardfree': 1, 'goorganic': 1,
             'mosquitorepellent': 1, 'kidsFavoriteMickeyMouse': 1, 'clearance': 1, 'designerjuttis': 1, 'Day2': 1,
             'thisdayinhistory': 1, '1may': 1, 'maharashtramaza': 1, 'garvigujarat': 1, 'proudindian': 1,
             'happymaharashtraday': 1, 'happygujaratday': 1, 'Blogging': 1, 'blogchatter': 1, 'bagsale': 1,
             'bagslover': 1, 'bagsaddict': 1, 'ThinkBig': 1, 'TuesdayTHoughts': 1, 'extendedsale': 1, 'publicdemand': 1,
             'offer': 1, 'juttiaddict': 1, 'handcraftedfootwear': 1, 'woodAndBamboo': 1, 'blindingSunglasses': 1,
             'roundframe': 1, 'BeatTheWinterSun': 1, 'MakeAFashionStatement': 1, 'motif': 1, 'pendant': 1, 'stunned': 1,
             'steady': 1, 'kada': 1, 'bangle': 1, 'TeddyDay': 1, 'Gowma': 1, 'egyptianEra': 1, 'singlezipper': 1,
             'ajustablesling': 1, 'fabricbags': 1, 'mondayinspiration': 1, 'puneentrepreneurs': 1, 'thriftingfinds': 1,
             'unstitchesClothing': 1, 'Swadesh': 1, 'dressmaterials': 1, 'Let': 1, 'bask': 1, 'rotating': 1, 'LED': 1,
             'lightlamp': 1, 'lights': 1, 'Order': 1, 'bagswithpurpose': 1, 'mybagmylife': 1, 'bagsthatfityourlife': 1,
             'bagsthatrock': 1, 'thestylestory': 1, 'bagsofstyle': 1, 'snakeskinbag': 1, 'snakeskinprint': 1,
             'snakeskinfashion': 1, 'bagslikeneverbefore': 1, 'bagsforsale': 1, 'bagsholic': 1, 'bagstyle': 1,
             'fashionbags': 1, 'Winters': 1, 'Enjoy': 1, 'crunchy': 1, 'tasty': 1, 'pakoras': 1, 'cup': 1,
             'masalachai': 1, 'aware': 1, 'constituents': 1, 'bring': 1, 'description': 1, 'Entrepreneurship': 1,
             'Inspirational': 1, 'QuoteOfTheDay': 1, 'MakeItHappen': 1, 'weddingdress': 1, 'DDay': 1, 'weddingideas': 1,
             'Designer': 1, 'boutiques': 1, 'leatherfashion': 1, 'leatheraccessories': 1, 'leatherWallet': 1,
             'leatherbelt': 1, 'HouseHunters': 1, 'lbloggers': 1, 'homedesign': 1, 'different': 1, 'First': 1,
             'Excellent': 1, 'quality': 1, 'freebasics': 1, 'NetNeutrality': 1, 'puneshopping': 1, 'foreignlanguage': 1,
             'education': 1, 'literature': 1, 'Germany': 1, 'Training': 1, 'schools': 1, 'retailers': 1,
             'semiwooden': 1, 'goldenmetalframe': 1, 'brownUVlenses': 1, 'regularfit': 1, 'returngiftideas': 1,
             'SpiceUp': 1, 'chocolate': 1, 'classylook': 1, 'indianclothing': 1, 'elegance': 1, 'pureleather': 1,
             'MakarSankranti': 1, 'IndianCelebratePongal': 1, 'LightUpHomes': 1, 'Diwali': 1, 'Products': 1,
             'SMTLive': 1, 'Santacruz': 1, 'khar': 1, 'mumbairains': 1, 'Gold': 1, 'bridalmakeup': 1, 'MOTD': 1,
             'IndianMasala': 1, 'HomemadeDelicacy': 1, 'tuesdaytip': 1, 'Customized': 1, 'spectaclecases': 1,
             'homegrown': 1, 'fabric': 1, 'wooden': 1, 'marblewatch': 1, 'marbledial': 1, 'thetribe': 1,
             'GoogleforIndia': 1, 'CheckRoutes': 1, 'Bedeck': 1, 'metal': 1, 'adorned': 1, 'TandooriWeekends': 1,
             'FoodFeverAtGharobar': 1, 'Set': 1, 'matching': 1, 'available': 1, 'Black': 1, 'purecotton': 1,
             'coldShoulder': 1, 'summerFashion': 1, 'diamondlike': 1, 'shiny': 1, 'edges': 1, 'heads': 1, 'coolbags': 1,
             'bugsbags': 1, 'wheelsbags': 1, 'footballfans': 1, 'quirkybags': 1, 'tribal': 1, 'Wearables': 1,
             'makememories': 1, 'gifitngideas': 1, 'mattersoftheheart': 1, 'woodenbox': 1, 'brasswork': 1,
             'wednesdaytips': 1, 'weekendsale': 1, 'home': 1, 'homehealth': 1, 'gorgeous': 1, 'payalvshankar': 1,
             'pink': 1, 'chickenkari': 1, 'salwarkameez': 1, 'saturdayshopping': 1, 'sunnysaturday': 1,
             'PuneConnect2016': 1, 'VeganProducts': 1, 'AnimalSkinFree': 1, 'NoCrueltyToAnimals': 1, 'SaveAnimals': 1,
             'ConfrenceBags': 1, 'HomeMade': 1, 'TuesdayThoughts': 1, 'TuesdayTip': 1, 'beautytips': 1,
             'naturalbeauty': 1, 'beautifulskin': 1, 'monsoontreatment': 1, 'tipstosurvivemonsoon': 1, 'monsoon': 1,
             'loveyourskin': 1, 'skincareproducts': 1, 'cleansing': 1, 'warmSummerNights': 1, 'festivals': 1,
             'creativity': 1, 'art': 1, 'midnight': 1, 'behindthescenes': 1, 'aundh': 1, 'empoweringwomeninbusiness': 1,
             'thisweekend': 1, 'Skill4jobs': 1, 'springsummer': 1, 'KidsGifts': 1, 'Toddlers': 1, 'Bags': 1,
             'SocksCumShoe': 1, 'stainlesssteel': 1, 'backtoschool': 1, 'happyindependenceday': 1, 'proudtobeindian': 1,
             'freedomthinkers': 1, 'positivechange': 1, 'Beauty': 1, 'epitome': 1, 'freshness': 1, 'hues': 1,
             'Kashmiri': 1, 'embroidered': 1, 'ribbon': 1, 'strings': 1, 'fresh': 1, 'fervour': 1, 'Fashionistas': 1,
             'usefulgifts': 1, 'timelessgifts': 1, 'memorablegifts': 1, 'friendsforever': 1, 'Antique': 1,
             'SilverJewellery': 1, 'goldjewellery': 1, 'Valentine': 1, 'TeddyBear': 1, 'stylequotient': 1,
             'bluejuttis': 1, 'homefurnishings': 1, 'comfyfurnishing': 1, 'fabrictrays': 1, 'servingtray': 1,
             'ouneinsta': 1, 'importedfabrics': 1, 'heavyblouse': 1, 'designed': 1, 'fridaymusings': 1, 'instagood': 1,
             'quotestagram': 1, 'quotesoftheday': 1, 'onedayiwill': 1, 'smallbusinessowners': 1, 'Pencil': 1, 'bag': 1,
             'sharpeners': 1, 'Attractive': 1, 'nontoxic': 1, 'easytouse': 1, 'lolmax': 1, 'cashburning': 1,
             'leanstartup': 1, 'TimesFood': 1, 'PCBP131': 1, 'all': 1, 'Snitch': 1, 'handmadesoaps': 1,
             'MyrahProducts': 1, 'weddinghour': 1, 'message': 1, 'Saree': 1, 'watctop100': 1, 'celebratefriendship': 1,
             'claimyourfreegift': 1, 'store': 1, 'friends': 1, 'eternalfashion': 1, 'lucknowiKurtis': 1,
             'summercollection': 1, 'differentflavours': 1, 'natural': 1, 'nourishment': 1, 'hydrateskin': 1,
             'jewelleryoftheday': 1, 'Diwaliweekend': 1, 'mondaymotivation': 1, 'birthdaycelebration': 1,
             'mentoring': 1, 'juttisale': 1, 'madeindia': 1, 'westend': 1, 'diwalishopping': 1, 'OnlineMarketing': 1,
             'Womenatwork': 1, 'gethydrated': 1, 'bottleholders': 1, 'summertime': 1, 'shoppingfest': 1, 'internet': 1,
             'Government': 1, 'SmartCity': 1, 'sparklers': 1, 'danglers': 1, 'weddingCollection': 1,
             'statementEarrings': 1, 'gemstone': 1, 'gems': 1, 'positiveenergy': 1, 'dailywear': 1, 'jewels': 1,
             'colorfulgems': 1, 'positivevibes': 1, 'social': 1, 'footfetishnation': 1, 'summertrends': 1,
             'ecofriendly': 1, 'organicdiaper': 1, 'norashes': 1, 'kashmiriHandicrafts': 1, 'sneakpeak': 1,
             'mensstyleinspiration': 1, 'mensWear': 1, 'summerShirts': 1, 'mensAccessories': 1, 'eternal': 1,
             'romantic': 1, 'date': 1, 'fathersdaygifts': 1, '16june2019': 1, 'fathersday': 1, 'cardholders': 1,
             'mensperfumes': 1, 'diaries': 1, 'italianleather': 1, 'tannedleather': 1, 'jobsAtGharobar': 1,
             'careersInEcommerce': 1, 'christmasweek': 1, 'christmas': 1, 'WelcomeBackMaggi': 1, 'jutti': 1,
             'flauntyourjuttis': 1, 'EmpoweringWomenInBusinesses': 1, 'GoalOriented': 1, 'friendshipdaymemes': 1,
             'cutemomentos': 1, 'makingmemories': 1, 'awesomegifts': 1, 'curios': 1, 'ExhibitionAlert': 1,
             'ChallengeYourLimits': 1, 'smallBusinessesGoBig': 1, 'madeIndia': 1, 'wroughtIronCrafts': 1, 'Ethnic': 1,
             'KurtaPyjama': 1, 'FestiveSeason': 1, 'ThankfulThursday': 1, 'indialove': 1, 'bun': 1, 'curls': 1,
             'hairstyle': 1, 'hairdo': 1, 'MakeupArtist': 1, 'prettylooking': 1, 'Golden': 1, 'shade': 1, 'Chennai': 1,
             'honeywell': 1, 'sales': 1, 'corporateflea': 1, 'traditionallysubmissive': 1, 'ethnicprofile': 1,
             'fashionweek': 1, 'christopoloindia': 1, 'buy1get1free': 1, 'shineon': 1, 'Womenshopping': 1, 'online': 1,
             'makeuptips': 1, 'makeupartist': 1, 'bohemianstyle': 1, 'stylestorybyraeez': 1, 'BlackAndSilverBeauty': 1,
             'GermanSilver': 1, 'ValentineGift': 1, 'NecklaceAndEarrings': 1, 'showyourloveforsmallbusiness': 1,
             'EmpoweringWomen': 1, 'iLoveShopping': 1, 'womensDaySale': 1, 'Collaboration': 1, 'EveryVoteMatters': 1,
             'VoteKarMaharashtra': 1, 'style': 1, 'Juttis': 1, 'designerbelts': 1, 'sequins': 1, 'FestivalSeason': 1,
             'GirlsOutfit': 1, 'Traditional': 1, 'jhumki': 1, 'jhumkilove': 1, 'chandbali': 1, 'goldplated': 1,
             'mangalsutra': 1, 'pendantsets': 1, 'beautifulpieces': 1, 'highgold': 1, 'matchmaking': 1, 'couple': 1,
             'dating': 1, 'marriage': 1, 'weddingplanner': 1, 'relationship': 1, 'kashmiriwork': 1, 'sarees': 1,
             'purecrepe': 1, 'sweater': 1, 'WinterWonderland': 1, 'winterweather': 1, 'Saturdayshopping': 1,
             'banglelove': 1, 'setof': 1, 'bangles': 1, 'rubies': 1, 'champagnestones': 1, 'beautifulbangles': 1,
             'winterJacket': 1, 'Pinkpolkadot': 1, 'kitty': 1, 'contemporaryhues': 1, 'kidsroomdecor': 1,
             'wallclocks': 1, 'alarmclocks': 1, 'clocks': 1, 'keepgoing': 1, 'multi': 1, 'diyaz': 1, 'giftbox': 1,
             'giveaway': 1, 'Bonanza': 1, 'warmth': 1, 'collide': 1, 'discounted': 1, 'designersari': 1, 'sixyards': 1,
             'NeverGiveUp': 1, 'LearnFromMistakes': 1, 'KeepTrying': 1, 'timelessclocks': 1, 'galloppinghorse': 1,
             'crystalclock': 1, 'limitedstock': 1, 'perfecthousewarminggift': 1, 'beautifulclocks': 1, 'travelers': 1,
             'travelessentials': 1, 'travelstyle': 1, 'traveladdict': 1, 'summervacation2019': 1,
             'travelaccessories': 1, 'travelbag': 1, 'saffronfacecleanser': 1, 'facecleanser': 1, 'kurtipalazzoset': 1,
             'kurtipantset': 1, 'shopaholics': 1, 'getshopping': 1, 'helpingsmallbusiness': 1,
             'keepingYourInfantsWarm': 1, 'cuteWinterCaps': 1, 'ContestAlert': 1, '1gmgoldjewellery': 1,
             'gemstonesjewelry': 1, 'beautifuldesigns': 1, 'dailywearchains': 1, 'handmadebeauties': 1,
             'colorsofindia': 1, 'snowflakes': 1, 'frozenblue': 1, 'gratitudepost': 1, 'manyshadesof': 1,
             'Beautiful': 1, 'Kundan': 1, 'Moti': 1, 'brass': 1, 'alloy': 1, 'DailyWear': 1, 'Partywear': 1,
             'smalbusinesses': 1, 'paintparty': 1, 'celebratingWithColors': 1, 'funWithPaints': 1, 'bohemian': 1,
             'Sharinghappiness': 1, 'SmallBusiness': 1, 'Delhi': 1, 'organic': 1, 'herbal': 1, 'Startup': 1,
             'saturdayvibes': 1, 'saynotoplastic': 1, 'healthyalternatives': 1, 'lunchboxes': 1, 'madeofsteel': 1,
             'leakproof': 1, 'creativework': 1, 'jewelsofindia': 1, 'puresilver': 1, 'nosepins': 1,
             'traditionaljewellery': 1, 'thejewelboxposts': 1, 'flauntjewelry': 1, 'traditionalthursday': 1,
             'trendythursdsy': 1, 'isayyes': 1, 'forboys': 1, 'Rakhi': 1, 'RakshaBandan': 1, 'Tuesday': 1,
             'wednesday': 1, 'wednesdaymotivation': 1, 'humpday': 1, 'happy': 1, 'picoftheday': 1, 'acoustic': 1,
             'factory': 1, 'wednedaymotivation': 1, 'bmcsoftware': 1, 'REDHour': 1, 'durable': 1, 'attractive': 1,
             'sharara': 1, 'germanSilver': 1, 'successmindset': 1, 'entrepreneurslife': 1, 'motivational': 1,
             'marketingdigital': 1, 'businessman': 1, 'GetItGirl': 1, 'diwali': 1, 'party': 1, 'cuckooclock': 1,
             'housewarminggift': 1, 'antiqueclocks': 1, 'organdonation': 1, 'FashionJewellery': 1, 'PendantOnScarf': 1,
             'weekendfleamarket': 1, 'winterClothing': 1, 'shoppingextravaganza': 1, 'foldingpenstand': 1, 'memopad': 1,
             'handmadediary': 1, 'stationaryholder': 1, 'windowbox': 1, 'BackToStoneAge': 1, 'redefine': 1,
             'lavender': 1, 'divas': 1, 'Xmastime': 1, 'LifeOfAnEntrepreneur': 1, 'UpsAndDowns': 1,
             'EmpoweringHomeBasedBusiness': 1, 'tribaljewellery': 1, 'jewelleryset': 1, 'handmadejewelleryforsale': 1,
             'ikkatbedsheets': 1, 'ikkatlove': 1, 'ikkatcollections': 1, 'ikkatprint': 1, 'cottonbedsheet': 1,
             'fashionshow': 1, 'WisdomWednesday': 1, 'PromiseForABetterTomorrow': 1, 'PromiseDay': 1,
             'fridayfashion': 1, 'styleststement': 1, 'clutches': 1, 'boxclutches': 1, 'grandsale': 1, 'Shopaholics': 1,
             'collaboration': 1, 'wallet': 1, 'amazingdiscounts': 1, 'women': 1, 'beautifulprints': 1,
             'vibrantcolours': 1, 'reasonblypriced': 1, 'racks': 1, 'NewYear': 1, 'Satisfaction': 1, 'newbeginnings': 1,
             'designers': 1, 'slingbags': 1, 'fashionablefridays': 1, 'funfridays': 1, 'slingfling': 1,
             'practicaldesign': 1, 'partyaccessories': 1, 'GST': 1, 'GSTForIndustry': 1, 'Infographics': 1,
             'sangeetSandhya': 1, 'weddingFashion': 1, 'tribe': 1, 'semiwood': 1, 'acetate': 1, 'antiquesilver': 1,
             'PreMoney': 1, 'thebigsale': 1, 'saleupto50': 1, 'sarisale': 1, 'adimaa': 1, 'kanthasari': 1,
             'parsigara': 1, 'linensaris': 1, 'bandhinisaris': 1, 'lehiriya': 1, 'wheredreamscometrue': 1,
             'summermusings': 1, 'baglover': 1, 'greatbag': 1, 'abagtoupliftyourmood': 1, 'handbaglove': 1, 'upto45': 1,
             'sariforallseasons': 1, 'kidsShopping': 1, 'bedazzled': 1, 'empoweringwomen': 1, 'payalscribbles': 1,
             'whenindoubtwhereasari': 1, 'gotapattisaree': 1, 'indianwedding': 1, 'iloveindia': 1, 'ilovesari': 1,
             'indianhandicrafts': 1, 'indianhandloom': 1, 'FDI': 1, 'afghanjewelleryinindia': 1, 'oxidizedjewellery': 1,
             'chunkyjewellery': 1, 'punebloggers': 1, 'flat500': 1, 'Mompreneur': 1, 'Icantdo': 1, 'gola': 1,
             'staysunsafe': 1, 'styleicon': 1, 'SafeHoli': 1, 'softtoybags': 1, 'differentdesign': 1,
             'cartooncharacters': 1, 'easy': 1, 'carry': 1, 'school': 1, 'CreateTraffic': 1, 'MondayMotivation': 1,
             'Winter': 1, 'winterpartymoment': 1, 'homemadechristmas': 1, 'saffronthreads': 1, 'imported': 1,
             'richcolour': 1, 'delightfularoma': 1, 'confirmedquality': 1, 'MadeByHer': 1, '41': 1, 'retailoutlet': 1,
             'gotapatti': 1, 'amazingfootwear': 1, 'sapphirering': 1, 'sapphireengagementring': 1, 'whatwomenlove': 1,
             'jewellerylover': 1, 'touch': 1, 'flavour': 1, 'room': 1, 'goodnight': 1, 'sleep': 1,
             'helpingHomeBasedBusinesses': 1, 'stayshady': 1, 'shades': 1, 'Sankranti': 1, 'indiacelebratespongal': 1,
             'fairyfeel': 1, 'georgette': 1, 'kashmiri': 1, 'embroidery': 1, 'feet': 1, 'socks': 1,
             'GooglyWooglyWooksh': 1, 'Natural': 1, 'IdeaOfTheDay': 1, 'businesses': 1, 'deAsra': 1, 'ForBoys': 1,
             'Girls': 1, 'indowesternclothing': 1, 'childrensday': 1, 'rakhishopping': 1, 'rakhis': 1,
             'brothersisterbond': 1, 'cushions': 1, 'WinterHeat': 1, 'HappyNewYear': 1, 'silvostyle': 1, 'jwellery': 1,
             'homefurnishing': 1, 'kidsaccessories': 1, 'schoolutilities': 1, 'smallbusinessowner': 1,
             'businessowners': 1, 'businesswomen': 1, 'businessmen': 1, 'newbusiness': 1, 'businesspassion': 1,
             'localbusiness': 1, 'businesscards': 1, 'shopsmallbusiness': 1, '4Daysfor2017': 1, 'AreYouReady': 1,
             'shoponline': 1, 'nextdaydelivery': 1, 'mom': 1, 'Entrepreneurs': 1, 'batik': 1, 'valentine': 1,
             'birthday': 1, 'anniversary': 1, 'skinfriendly': 1, 'stockclearance': 1, 'kurtiset': 1,
             'unstitchedothing': 1, 'Apple': 1, 'iphone6': 1, 'styleblogger': 1, 'secretcrush': 1, 'WomenAtWork': 1,
             'freegift': 1, 'lucknowis': 1, 'indowestern': 1, 'semistitchedclothing': 1, 'sarishopping': 1,
             'sarisaturday': 1, 'withlove': 1, 'silks': 1, 'satins': 1, 'georgettesaree': 1, 'chiffonsaree': 1,
             'velvets': 1, 'branding': 1, 'marketing': 1, 'mindset': 1, 'brand': 1, 'wednesdayfinds': 1,
             'vegetabledyed': 1, 'cotton': 1, 'silkcotton': 1, 'decor': 1, 'JoinUs': 1, 'mensaccessories': 1,
             'bridal': 1, 'giftideas': 1, 'packagingdesign': 1, 'instadaily': 1, 'saturdaysensation': 1,
             'supersaturday': 1, 'juttismadewithlove': 1, 'Janmashtami': 1, 'HappyJanmashtami': 1, 'KnowOurSeller': 1,
             'GaneshChaturti': 1, 'GaneshFestival': 1, 'LordGanesha': 1, 'sangeetFashion': 1, 'Navratri': 1,
             'Fashion': 1, 'happycustomers': 1, 'curated': 1, 'day2': 1, 'Toast2015': 1, 'mind': 1, 'soul': 1,
             'healthcare': 1, 'meditation': 1, 'counselor': 1, 'LiveLifeLaughing': 1, 'newyearsresolution': 1,
             'Navami': 1, 'chemicalFreebeautyproducts': 1, 'BodyPolish': 1, 'BeautyThatisSkinDeep': 1, 'ILoveCoffee': 1,
             'leathergoods': 1, 'savewildlife': 1, 'saveanimals': 1, 'gowma': 1, 'FortuneMagic': 1, 'tarot': 1,
             'FutureDecoded': 1, 'explore': 1, 'happyJanmashtami': 1, 'bigsale': 1, 'leatherwallets': 1,
             'menswallets': 1, 'businessopportunity': 1, 'SmallBusinessesGoBig': 1, 'businesslife': 1, 'mlm': 1,
             'affiliatemarketing': 1, 'Perfume': 1, 'adstudded': 1, 'heartbeat': 1, 'dilkidhadkan': 1, 'lovestruck': 1,
             'cutebracelet': 1, 'designerbracelet': 1, 'braceletlove': 1, 'braceletswag': 1, 'braceletlover': 1,
             'braceletoftheday': 1, 'braceletfantasy': 1, 'SocialMediaMarketing': 1, 'sister': 1, 'unstitchedsuits': 1,
             'semiformaloutfit': 1, 'ethnicjackets': 1, 'stole': 1, 'watch': 1, 'smm': 1, 'Bangles': 1,
             'worshipmyfeet': 1, 'blessed': 1, 'money': 1, 'hardwork': 1, 'grind': 1, 'ambition': 1, 'millionaire': 1,
             'luxury': 1, 'wealth': 1, 'work': 1, 'dreams': 1, 'boss': 1, 'dedication': 1, 'music': 1, 'empreender': 1,
             'hustle': 1, 'summervibes': 1, 'indiansummer': 1, 'beaththeheat': 1, 'kutch': 1, 'ajrakh': 1, 'mashru': 1,
             'timelessstyle': 1, 'wristwatch': 1, 'womensaccessories': 1, 'classywatches': 1, 'Blooddonor': 1,
             'Help': 1, 'mumbaiblooddonors': 1, 'SEO': 1, 'desi': 1, 'designerbrands': 1, 'NewYearParty': 1,
             'eidoutfit': 1, 'eidjewellery': 1, 'momlife': 1, 'indiantraditionaljewellery': 1, 'revivingtraditions': 1,
             'kundanjewellery': 1, 'paasa': 1, 'maangtikka': 1, 'toering': 1, 'handjewellery': 1,
             'handchainringbracelet': 1, 'handchainbracelet': 1, 'haathphool': 1, 'leafy': 1, 'veggies': 1,
             'plastic': 1, 'brush': 1, 'gift': 1, 'box': 1, 'BoxingDay': 1, 'ChristmasAtHome': 1, 'makeInIndia': 1,
             'charcoalsoap': 1, 'narural': 1, 'nofoamingagent': 1, 'nourishing': 1, 'soften': 1, 'glowing': 1,
             'goodquality': 1, 'waterproof': 1, 'rayonfabric': 1, 'differentcolour': 1, 'trendsetter': 1,
             'bethebest': 1, 'gala': 1, 'affair': 1, 'suavelook': 1, 'practicaldesigns': 1, 'laptopbag': 1,
             'trendythursdays': 1, 'puneinstagrammees': 1, 'navratri': 1, 'cupcake': 1, 'dessert': 1, 'NoExcuses': 1,
             'SaySomethingSweet': 1, 'OOTD': 1, 'StatementNeckPiece': 1, 'jackets': 1, 'EidMubarak': 1,
             'WellnessWednday': 1, 'BloggingGals': 1, 'officeaccesories': 1, 'fashionjewellery': 1,
             'IgniteTheExcitement': 1, 'हर_क': 1, 'kidsWinterFashion': 1, 'winterWear': 1, 'valentinesDay': 1,
             'dazzlers': 1, 'giftsForHer': 1, 'goodbye': 1, '500note': 1, 'rolls': 1, 'redcarpet': 1, 'welcome': 1,
             'Watch': 1, 'Buynow': 1, 'orderly': 1, 'eCommerceSolution': 1, 'eshopy': 1, 'BuyOnline': 1, 'buynow': 1,
             'ChennaiRains': 1, 'weddingsari': 1, 'velvetsari': 1, 'blacksari': 1, 'fashionfriday': 1, 'ilovesaris': 1,
             'vintagecollection': 1, 'grandfatherclock': 1, 'relivingchildhoodfantasies': 1, 'oldisgold': 1,
             'LearnFromCompetitiors': 1, 'FridayFeeling': 1})
        counter2 = Counter(
            {'gharobar': 143, 'smallbusinessesgobig': 131, 'Gharobar': 87, 'madeinindia': 84, 'puneinstagrammers': 66,
             'puneinsta': 62, 'punetimes': 61, 'jewellery': 28, 'fashionista': 27, 'FlagshipStore': 26, 'sale': 25,
             'dorabjeesmall': 23, 'juttis': 23, 'EmpoweringEntrepreneurs': 21, 'giftingideas': 20,
             'SmallBusinessesGoBig': 20, 'pune': 18, 'bags': 18, 'handmade': 18, 'salealert': 17, 'fashion': 16,
             'homedecor': 16, 'onsale': 16, 'love': 14, 'juttiswag': 14, 'raeezjuttis': 14, 'silverjewellery': 13,
             'handicrafts': 13, 'punefashion': 13, 'SneakPeak': 13, 'Offers': 13, 'shopaholic': 13, 'gifts': 12,
             'HomeBasedSellers': 12, 'Sale': 12, 'cutegifts': 11, 'friendshipday': 10, 'pocketfriendly': 10,
             'friendsforever': 10, 'skincare': 10, 'lowestpriceever': 10, 'clearancesale': 10, 'fridayfunday': 10,
             'india': 10, 'usefulgifts': 9, 'timelessgifts': 9, 'memorablegifts': 9, 'indianjewellery': 9,
             'ethnicjewellery': 9, 'Ecommerce': 9, 'weddingseason': 9, 'thestylestorybyraeez': 9, 'clothing': 9,
             'summersale': 9, 'multibrand': 9, 'retailstore': 9, 'Discount': 9, 'Pune': 9, 'accessories': 8,
             'entrepreneur': 8, 'footwear': 8, 'shopping': 8, 'handcrafted': 8, 'SmallBusinesses': 8,
             'sundayshopping': 8, 'EndOfSeasonSale': 8, 'shop': 7, 'Soaps': 7, 'shoppingaddict': 7, 'photooftheday': 7,
             'smallbusinesses': 7, 'celebritystyle': 7, 'tuesdayvibes': 7, 'amulyamjewels': 7, 'Discounts': 7,
             'Christmas': 7, 'India': 7, 'kurtis': 7, 'wallets': 6, 'retailtherapy': 6, 'discounts': 6,
             'smallbusiness': 6, 'TFLers': 6, 'instagood': 6, 'business': 6, 'mondayvibes': 6, 'punjabijutti': 6,
             'designer': 6, 'Adimaa': 6, 'juttilove': 6, 'punebloggers': 6, 'style': 6, 'weddingjewellery': 6,
             'saris': 6, 'sarinotsorry': 6, 'earrings': 5, 'motivation': 5, 'fashionistas': 5, 'natural': 5,
             'christopolo': 5, 'life': 5, 'instadaily': 5, 'nofilter': 5, 'TGIF': 5, 'Entrepreneur': 5,
             'businessowner': 5, 'CustomerIsKing': 5, 'inspiration': 5, 'avadh': 5, 'silver': 5, 'weddingshopping': 5,
             'bagswag': 5, 'supportsmallbusiness': 5, 'designerjewellery': 5, 'sari': 5, 'indiheart': 5, 'SkinCare': 5,
             'kids': 5, 'NewYearSale': 5, 'bedsheets': 5, 'designersaris': 5, 'Organic': 5, 'ChristmasSale': 5,
             'indian': 5, 'pamperyourfeet': 5, 'HomeBasedSeller': 5, 'schoolsupplies': 4, 'Hustle': 4, 'handbag': 4,
             'handbags': 4, 'fitness': 4, 'indianhandicrafts': 4, 'chic': 4, 'leather': 4, 'dufflebags': 4,
             'Christopolo': 4, 'KnowTheBrand': 4, 'Bath': 4, 'HomeDecor': 4, 'entrepreneurlife': 4, 'leatherbelts': 4,
             'quoteoftheday': 4, 'entrepreneurship': 4, 'onlinemarketing': 4, 'businesstips': 4, 'businesswoman': 4,
             'digitalmarketing': 4, 'handicraftsofindia': 4, 'iloveshopping': 4, 'designerjuttis': 4,
             'indianwedding': 4, 'gift': 4, 'indianfashion': 4, 'ilovebags': 4, 'watches': 4, 'freegift': 4,
             'anniversarygift': 4, 'newArrivals': 4, 'sunflowercreations': 4, 'followback': 4, 'Kutch': 4,
             'beattheheat': 4, 'newyear': 4, 'Jewellery': 4, 'weddingfashion': 4, 'popupsale': 4, 'perfumes': 4,
             'thejewelbox': 4, 'vote': 4, 'DecemberSale': 4, 'wednesdayvibes': 4, 'Offer': 4, 'leatherbags': 4,
             'ethnicwear': 4, 'eidsale': 4, 'upto50': 4, 'SmallBusinessGoBig': 4, 'repost': 4, 'Handmade': 4,
             'OnlineShopping': 4, 'follow': 4, 'followme': 4, 'followforfollow': 4, 'follow4follow': 4, 'me': 4,
             'Shopping': 4, 'traditional': 4, 'raeez': 4, 'punelife': 4, 'sariswag': 4, 'quirkygifts': 3, 'amazing': 3,
             'WednesdayWisdom': 3, 'newarrivals': 3, 'fashionstatement': 3, 'healthy': 3, 'food': 3, 'cosmetics': 3,
             'gorgeous': 3, 'mensfashion': 3, 'thursdayvibes': 3, 'summer': 3, 'organic': 3, 'KnowTheSeller': 3,
             'MondayBlues': 3, 'amazingoffers': 3, 'flagshipstore': 3, 'offers': 3, 'dorabjeemall': 3,
             'endofseasonsale': 3, 'quotes': 3, 'tweegram': 3, 'igers': 3, 'instamood': 3, 'Shop': 3,
             'onlinebusiness': 3, 'hustle': 3, 'startups': 3, 'HomeBasedBusiness': 3, 'success': 3, 'goals': 3,
             'luxury': 3, 'lifestyle': 3, 'passion': 3, 'handblockprint': 3, 'shopfromsmallbusiness': 3,
             'celebration': 3, 'newcollection': 3, 'bracelet': 3, 'fashionblogger': 3, 'bagaddict': 3,
             'womensaccessories': 3, 'jewellerylover': 3, 'toys': 3, 'ootd': 3, 'bedsheetset': 3, 'bedsheetsinlagos': 3,
             'bedsheetsets': 3, 'Sports': 3, 'fleamarket': 3, 'likeforlikes': 3, 'puneshopping': 3, 'jhumkilove': 3,
             'glammedup': 3, 'sarisunday': 3, 'sundaysensation': 3, 'multibrandstore': 3, 'giftideas': 3, 'scarves': 3,
             'weddingaccessories': 3, 'BodyCare': 3, 'December': 3, 'homemade': 3, 'beautiful': 3, 'summerfashion': 3,
             'styleicon': 3, 'Store': 3, 'necklace': 3, 'summeressentials': 3, 'christopoloindia': 3,
             'festivalseason': 3, 'famousquotes': 3, 'slingbags': 3, 'jewelry': 3, 'fashionaccessories': 3,
             'abvatandabeyegabutton': 3, 'showyourinkedfinger': 3, 'festivalfashion': 3, 'Lucknawi': 3, 'Kurtis': 3,
             'goldjewellery': 3, 'silverjewellery925': 3, 'exclusive': 3, 'cottonsaris': 3, 'ShopOnline': 3,
             'discount': 3, 'kamakshistudio': 3, 'Jutis': 3, 'steelbottles': 3, 'leakproof': 3, 'waterbottles': 3,
             'Indian': 3, 'indowestern': 3, 'DryFruits': 3, 'mumbai': 3, 'kutchibags': 3, 'travelbag': 3,
             'statementjewellery': 3, 'Clothing': 3, 'freedomsale': 3, 'laptopbags': 3, 'kidsfashion': 3,
             'dressmaterials': 3, 'madeInIndia': 3, 'comfort': 3, 'NewYear': 3, 'festival': 3, 'f4f': 3,
             'teamfollowback': 3, 'followher': 3, 'followbackteam': 3, 'followhim': 3, 'followall': 3,
             'followalways': 3, 'pleasefollow': 3, 'follows': 3, 'follower': 3, 'following': 3, 'onlineshopping': 3,
             'shoptillyoudrop': 3, 'Handcrafted': 3, 'sunglasses': 3, 'mirrorwork': 3, 'ethnic': 3,
             'indowesternclothing': 3, 'silveranklets': 2, 'jewelsofindia': 2, 'puresilver': 2,
             'traditionaljewellery': 2, 'thejewelboxposts': 2, 'grandopening': 2, 'elegant': 2, 'semipreciousstones': 2,
             'sequencebags': 2, 'cutebags': 2, 'fashionnova': 2, 'purses': 2, 'fashionbags': 2, 'girlsfashion': 2,
             'blingybackpack': 2, 'backpack': 2, 'sequencebackpacks': 2, 'backpacks': 2, 'sling': 2,
             'crossbodysling': 2, 'dryfruits': 2, 'healthylifestyle': 2, 'winter': 2, 'PopUpShow': 2, 'antique': 2,
             'wallhanging': 2, 'stylish': 2, 'belts': 2, 'men': 2, 'genuineleather': 2, 'laptopbag': 2,
             'thestylestory': 2, 'EmpoweringHomeBasedSellers': 2, 'EmpoweringEntrepreneur': 2, 'shoppingbonanza': 2,
             'christmas': 2, 'quote': 2, 'comment': 2, 'comments': 2, 'song': 2, 'funny': 2, 'instagramhub': 2,
             'tbt': 2, 'true': 2, 'word': 2, 'EmpoweringSmallBusinesses': 2, 'TipTuesday': 2, 'startup': 2,
             'successmindset': 2, 'entrepreneurslife': 2, 'motivational': 2, 'marketingdigital': 2, 'money': 2,
             'hardwork': 2, 'grind': 2, 'ambition': 2, 'millionaire': 2, 'wealth': 2, 'work': 2, 'dreams': 2, 'boss': 2,
             'dedication': 2, 'music': 2, 'empreender': 2, 'hiphop': 2, 'alcancesuasmetas': 2, 'kurtapalazzosets': 2,
             'cushioncovers': 2, 'homefurnishings': 2, 'makarsankranti': 2, 'january': 2, 'sankranti': 2,
             'instagram': 2, 'kite': 2, 'jootis': 2, 'celebstyle': 2, 'highgold': 2, 'gold': 2, 'clocks': 2,
             'wallclocks': 2, 'grandfatherclock': 2, 'housewarminggift': 2, 'womensfashion': 2, 'dailywearearrings': 2,
             'silverearrings': 2, 'jewellerydesign': 2, 'ilovejewellery': 2, 'lucknowi': 2, 'chikankari': 2,
             'festivesale': 2, 'kutch': 2, 'GymEquipments': 2, 'supersunday': 2, 'sundayfunday': 2, 'Raeez_juttis': 2,
             'fleamarketpune': 2, 'punefleamarket': 2, 'punefarmersmarket': 2, 'bathboons': 2, 'bathproducts': 2,
             'skincareroutine': 2, 'weekendvibes': 2, 'puneweekend': 2, 'Exhibitionalert': 2, 'B4': 2, 'exhibition': 2,
             'puneflea': 2, 'westernclothes': 2, 'punekar': 2, 'kantha': 2, 'tribaljewellery': 2, 'ilovejewelry': 2,
             'statementearrings': 2, 'statementnecklace': 2, 'swadesh': 2, 'importedfabrics': 2, 'designed': 2,
             'instalike': 2, 'sequin': 2, 'dailywear': 2, 'Endofseasonsale': 2, 'footfetishnation': 2, 'jhumkaswag': 2,
             'earringsoftheday': 2, 'earringsforsale': 2, 'monsoonsale': 2, 'heartshaped': 2, 'wednesdaytips': 2,
             'shopsmall': 2, 'lowestprice': 2, 'pureleather': 2, 'shoplocal': 2, 'smallBusinessesGoBig': 2, 'stoles': 2,
             'summerswag': 2, 'sunprotection': 2, 'happynewyear': 2, 'Resolutions': 2, 'festivalshopping': 2,
             'HomeMade': 2, 'TuesdayThoughts': 2, 'HandCrafted': 2, 'Luxury': 2, 'ShoppingOnline': 2, 'design': 2,
             'theadorables': 2, 'fashionaddict': 2, 'slipons': 2, 'formen': 2, 'buy1get1free': 2, 'beauty': 2,
             'retailer': 2, 'Bags': 2, 'HandMade': 2, 'Avadh': 2, 'funfridays': 2, 'customisedbags': 2, 'mothersday': 2,
             'designerwear': 2, 'kidsaccessories': 2, 'fashionkids': 2, 'chandbali': 2, 'oxidisedjewellery': 2,
             'nightwear': 2, 'empoweringwomen': 2, 'silksaris': 2, 'Food': 2, 'HealthyLiving': 2, 'pasta': 2,
             'EndOfSeason': 2, 'wintercare': 2, 'diva': 2, 'Santa': 2, 'Footwear': 2, 'unstitchedclothing': 2,
             'fashionjewelry': 2, 'elegance': 2, 'Party': 2, 'foodisbae': 2, 'bagshopping': 2, 'Almonds': 2,
             'highgoldjewellery': 2, 'socialmediamarketing': 2, 'smallbusinessowners': 2, 'businessopportunity': 2,
             'marketingtips': 2, 'businesslife': 2, 'businessman': 2, 'Silver': 2, 'SilverJewellery': 2,
             'Accessories': 2, 'Natural': 2, 'Necklace': 2, 'flat20': 2, 'Kisha': 2, 'shopaholics': 2, 'craftsmen': 2,
             'kutchijackets': 2, 'gems': 2, 'jewels': 2, 'travelessentials': 2, 'travelers': 2, 'baglover': 2,
             'stylestory': 2, 'Diwali': 2, 'WesternOutfits': 2, 'free': 2, 'bedsheetsinabuja': 2, 'rakshabandhan': 2,
             'rakhis': 2, 'saturdaysensation': 2, 'saturdaystyle': 2, 'raeez_juttis': 2, 'motivationalquotes': 2,
             'salwarkameez': 2, 'eidshopping': 2, 'fashionjewelleryandaccessories': 2, 'bohostyle': 2,
             'bohemianstyle': 2, 'rakhishopping': 2, 'cardholders': 2, 'tannedleather': 2, 'inspirationalquotes': 2,
             'wallet': 2, 'CushionCovers': 2, 'LivingRoom': 2, 'KidsApparel': 2, 'instababy': 2, 'indianwear': 2,
             'banarasidupatta': 2, 'bigsale': 2, 'menswallets': 2, 'last2days': 2, 'partyaccessories': 2, 'offer': 2,
             'sorkhzar': 2, 'toddlers': 2, 'MadeInIndia': 2, 'ValentinesWeekSale': 2, 'Customized': 2, 'bedspread': 2,
             'gudi': 2, 'supersale': 2, 'phulkari': 2, 'BathSalts': 2, 'Nourish': 2, 'silvertrinklets': 2,
             'traveladdict': 2, 'quotestoliveby': 2, 'family': 2, 'elections2019': 2, 'bearesponsiblecitizen': 2,
             'Kashmiri': 2, 'madeofsteel': 2, 'backtoschool': 2, 'diwali': 2, 'navratri': 2, 'i': 2, 'diwalidecor': 2,
             'festive': 2, 'deepavali': 2, 'decoration': 2, 'wedding': 2, 'indianmomblogger': 2, 'sangeet': 2,
             'indiansinlondon': 2, 'interiordesign': 2, 'festivals': 2, 'fabindianews': 2, 'bhfyp': 2, 'motiwork': 2,
             'like4like': 2, 'shopnow': 2, 'indianhomedecor': 2, 'zariwork': 2, 'gotapattiwork': 2, 'sequins': 2,
             'decembersale': 2, 'clothes': 2, 'ladyinred': 2, 'Jackets': 2, 'fashionable': 2, 'puneblogger': 2,
             'shoes': 2, 'ghaorbar': 2, 'ecommerce': 2, 'comingsoon': 2, 'smile': 2, 'picoftheday': 2, 'girl': 2,
             'bestoftheday': 2, 'independenceday': 2, 'elitepune': 2, 'madeindia': 2, 'silvernecklace': 2,
             'GiftCards': 2, 'kidslovecars': 2, 'branding': 2, 'thursdaytrends': 2, 'gotapatti': 2,
             'handcraftedjuttis': 2, 'eidmubarak': 2, 'fashionstyle': 2, 'instafashion': 2, 'shades': 2, 'happy': 2,
             'jewelrydesigner': 2, 'jewelryaddict': 2, 'retailoutlet': 2, 'potlibags': 2, 'jewelleryoftheday': 2,
             'fleamarkets': 1, 'ankletswag': 1, 'prettyfeet': 1, 'ankletlove': 1, 'loveforjewellery': 1, 'nosepins': 1,
             'flauntjewelry': 1, 'traditionalthursday': 1, 'trendythursdsy': 1, 'GoalOriented': 1, 'mensapparel': 1,
             'madeIndia': 1, 'introducingNewSmallBusiness': 1, 'mensCasualWear': 1, 'mensaccessoriesshop': 1,
             'Kamakshi': 1, 'simple': 1, 'motherofpearl': 1, 'sequencebag': 1, 'transparentbag': 1,
             'transpaeentbags': 1, 'purse': 1, 'bag': 1, 'fashionbag': 1, 'girlbag': 1, 'girlbags': 1, 'pouch': 1,
             'pouches': 1, 'girly': 1, 'Dryfruits': 1, 'dryfruitsbowl': 1, 'dryfruitsandnuts': 1, 'healthyfood': 1,
             'fit': 1, 'foodporn': 1, 'kashmir': 1, 'highest': 1, 'quality': 1, 'happiness': 1, 'goodvibes': 1,
             'nutrition': 1, 'beinghealthy': 1, 'healthandfitness': 1, 'healthandhappiness': 1, 'showfoodz': 1,
             'thewalkfoodiecrawl': 1, 'worldmarkdelhi': 1, 'cheese': 1, 'cake': 1, 'cheesecake': 1, 'cakelover': 1,
             'grandsale': 1, 'Shopaholics': 1, 'collaboration': 1, 'indianstyles': 1, 'giftingIdeas': 1, 'brass': 1,
             'authenticindiancrafts': 1, 'Rajasthani': 1, 'smallbusinessgobig': 1, 'housewarminggifts': 1,
             'bblogger': 1, 'beautybasics': 1, 'beautyblogger': 1, 'dressyourface': 1, 'eyes': 1, 'eyeshadow': 1,
             'glam': 1, 'hairstyle': 1, 'hairstyles': 1, 'hudabeauty': 1, 'instabeauty': 1, 'instamakeup': 1,
             'lashes': 1, 'lips': 1, 'lipstick': 1, 'makeupaddict': 1, 'makeupjunkie': 1, 'makeuplover': 1, 'motd': 1,
             'mua': 1, 'nailart': 1, 'styles': 1, 'wakeupandmakeup': 1, 'mensaccessories': 1, 'suavelook': 1,
             'practicaldesigns': 1, 'crossby': 1, 'trendythursdays': 1, 'puneinstagrammees': 1, 'Fragnance': 1,
             'honey': 1, 'oats': 1, 'rose': 1, 'lemongrass': 1, 'vitamin': 1, 'bestsoaps': 1, 'shoponline': 1,
             'beatTheHeat': 1, 'exquisitescarves': 1, 'fashionableSummers': 1, 'handpicked': 1, 'bodycare': 1,
             'bodycaregrosir': 1, 'bodycareinnigeria': 1, 'bodycarepromo': 1, 'bodycareproducts': 1, 'bodycaremurah': 1,
             'bodycareonlineshop': 1, 'bodycareinlagos': 1, 'bodycarethailand': 1, 'bodycareset': 1, 'bodycarebpom': 1,
             'bodycarecenter': 1, 'bodycarejogja': 1, 'bodycareHN': 1, 'bodycarebodyshop': 1, 'bodycareherbal': 1,
             'bodycarejafra': 1, 'bodycarenuskin': 1, 'bodycarehudv': 1, 'bodycareoriflame': 1, 'hbwhitening': 1,
             'hbwhiteningplatinum': 1, 'hbwhiteningplatinumsuper': 1, 'bodywhiteninglotion': 1, 'whitening': 1,
             'lotionpemutihbadan': 1, 'lotionpemutih': 1, 'Flagshipstore': 1, 'Bathsalts': 1, 'Bedsheets': 1,
             'CushioCovers': 1, 'Covers': 1, 'SmallBusinesessGoBig': 1, 'empoweringentrepreneurs': 1,
             'showyourloveforsmallbusiness': 1, 'friendshipdaymemes': 1, 'cutemomentos': 1, 'makingmemories': 1,
             'awesomegifts': 1, 'curios': 1, 'celebratingfriendship': 1, 'bff': 1, 'gharobarstore': 1,
             'helpingHomeBasedBusinesses': 1, 'december': 1, 'designerbelts': 1, 'ChallengeYourLimits': 1,
             'ParsiNewYear': 1, 'FollowFriday': 1, 'Gandhi150': 1, 'GandhiJayanti': 1, 'entrepreneurs': 1,
             'entrepreneurlifestyle': 1, 'successquotes': 1, 'internetmarketing': 1, 'happyJanmashtami': 1,
             'woodencurios': 1, 'ikkatbedsheets': 1, 'ikkatlove': 1, 'ikkatcollections': 1, 'ikkatprint': 1,
             'cottonbedsheet': 1, 'LearnFromCompetitiors': 1, 'FridayFeeling': 1, 'bodybuilding': 1, 'happyshoppers': 1,
             'likemomlikeSon': 1, 'ourRockstar': 1, 'bagShopping': 1, 'handmadeBags': 1, 'mondayrules': 1,
             'stayclassy': 1, 'semiformalwear': 1, 'indianethnicwear': 1, 'cottonclothing': 1, 'kashmirihandicrafts': 1,
             'cushionsaddcolour': 1, 'giftsfromindia': 1, 'makarsankrati': 1, 'MakarSankranti': 1, 'Sun': 1,
             'RotationOfSun': 1, 'TheChateauGarli': 1, 'sun': 1, 'moon': 1, 'theday': 1, 'wish': 1, 'wishes': 1,
             'insta': 1, 'instamonday': 1, 'mykraft': 1, 'kites': 1, 'kitesfestival': 1, 'utrayan': 1, 'patang': 1,
             'colourfulsky': 1, 'colourfullindia': 1, '14january': 1, 'happymakarsankranti': 1, 'happyuttarayan': 1,
             'Makarsankranti': 1, 'Uttarayana2019': 1, 'uttarayan2k19': 1, 'needledust': 1,
             'NeedledustSelectCitywalk': 1, 'NeedledustNewStore': 1, 'Needledustjuttis': 1, 'mojri': 1, 'khussa': 1,
             'loveforshoes': 1, 'goldjuttis': 1, 'versatilityofNeedledustJuttis': 1, 'indianbride': 1, 'bridesmaids': 1,
             'mehndigifts': 1, 'weddingshoes': 1, 'handicraft': 1, 'houseofvianonsale': 1, 'shippingworldwide': 1,
             'delhishopping': 1, 'jewelleryonsale': 1, 'topshop': 1, 'forsale': 1, 'like': 1, 'victorianera': 1,
             'tableclock': 1, 'antiqueclock': 1, 'snakeskinbag': 1, 'snakeskinprint': 1, 'snakeskinfashion': 1,
             'bagslikeneverbefore': 1, 'bagsforsale': 1, 'bagsholic': 1, 'bagstyle': 1, 'timelessstyle': 1,
             'wristwatch': 1, 'classywatches': 1, 'pure': 1, 'gemstones': 1, 'customise': 1, 'stone': 1,
             'empowerment': 1, 'jewelery': 1, 'sportsgear': 1, 'jams': 1, 'trendy': 1, 'diwalisale': 1,
             'CottonJewellery': 1, 'CottonThreadJewellery': 1, 'FashionJewellery': 1, 'Earings': 1, 'CottonBeads': 1,
             'flat350': 1, 'flat800': 1, 'bedsheetstore': 1, 'bedsheetshabby': 1, 'bedsheetsph': 1, 'bedsheetsingle': 1,
             'bedsheetsetquiltcover': 1, 'bedsheetsinnigeria': 1, 'bedsheetsurabaya': 1, 'bedsheetseller': 1,
             'cottonbedsheets': 1, 'bedsheetsexpress': 1, 'bedsheetsforsal': 1, 'bedsheets_lk': 1,
             'designerbedsheets': 1, 'satinbedsheets': 1, 'bedsheetsetph': 1, 'bedsheetsuperking': 1,
             'bedsheetsindia': 1, 'bedsheetsonline': 1, 'bedsheetsimple': 1, 'doublebedsheets': 1, 'whitebedsheets': 1,
             'bedsheetsale': 1, 'vintagebedsheets': 1, 'silkbedsheets': 1, 'SportsEquipments': 1, 'Gym': 1, 'Shaker': 1,
             'Footbal': 1, 'Badminton': 1, 'Carrom': 1, 'Poker': 1, 'Skates': 1, 'BoardGames': 1, 'Cards': 1,
             'Sippers': 1, 'Nike': 1, 'Nivia': 1, 'celebratefriendship': 1, 'claimyourfreegift': 1, 'store': 1,
             'friends': 1, 'mobileslings': 1, 'glitterslings': 1, 'ilovebling': 1, 'Shofiesm': 1,
             'contestAnnouncement': 1, 'shoefiesm': 1, 'kanthasaree': 1, '5yardlovestory': 1, 'handembroidery': 1,
             'Kanthasaree': 1, 'loveforsaree': 1, 'indiansaree': 1, 'indianculture': 1, 'helpweavers': 1,
             'buyonline': 1, 'buysarionline': 1, 'silksari': 1, 'bengalart': 1, 'sareelovers': 1, 'animalkantha': 1,
             'handpainted': 1, 'handembroidered': 1, 'yellowsaree': 1, 'sareelover': 1, '100saripact': 1,
             '100sareepact': 1, 'bengalsaree': 1, 'artofindia': 1, 'paintingsofindia': 1, 'jutti': 1,
             'flauntyourjuttis': 1, 'tuesdaytrends': 1, 'tribaltuesday': 1, 'tribalhues': 1, 'jhumkiswag': 1,
             'jhumkis': 1, 'sneakpeak': 1, 'mensstyleinspiration': 1, 'mensWear': 1, 'summerShirts': 1,
             'mensAccessories': 1, 'heavyblouse': 1, 'gimmejuttis': 1, 'productshoot': 1, 'footweardesign': 1,
             'instagramers': 1, 'instashoes': 1, 'instashopping': 1, 'instalook': 1, 'follow4followback': 1,
             'followus': 1, 'modestwear': 1, 'chiffon': 1, 'handmadewithlove': 1, 'custommade': 1, 'passportcover': 1,
             'customized': 1, 'handmadegifts': 1, 'thisdayinhistory': 1, '1may': 1, 'maharashtramaza': 1,
             'garvigujarat': 1, 'proudindian': 1, 'happymaharashtraday': 1, 'happygujaratday': 1, 'cottonscarf': 1,
             'allpurpose': 1, 'weatherprotector': 1, 'pricelessjewellery': 1, 'antiquefinishjewellery': 1,
             'limitededitionjewellery': 1, 'classy': 1, 'elite': 1, 'studdedjewellery': 1, 'myprecious': 1,
             'homemademasala': 1, 'spiceupyourday': 1, 'sitarschettinadgheeroastmasala': 1,
             'sitarschettinadchickengheeroastmasala': 1, 'sitarschettinadmuttongheeroastmasala': 1,
             'sitarschettinadprawngheeroastmasala': 1, 'simplecooking': 1, 'easycooking': 1, 'vegemeal': 1,
             'vegetarianmeal': 1, 'vegelovers': 1, 'foodies': 1, 'vegerecipe': 1, 'kidsfavourite': 1, 'mommies': 1,
             'homemadeproduct': 1, 'currypowder': 1, 'gheeroastmasala': 1, 'originalchettinadmasala': 1,
             'malaysiaproduct': 1, 'masalalovers': 1, 'indianfood': 1, 'malaysiacurrypowder': 1, 'lessstress': 1,
             'cookingplan': 1, 'sitarsspice': 1, 'sitars': 1, 'longbeans': 1, 'garammasala': 1, 'styleblogger': 1,
             'cuteschoolsupplies': 1, 'handpaintedearrings': 1, 'longearrings': 1, 'earringswag': 1, 'earringlove': 1,
             'earringaddict': 1, 'earringslover': 1, 'earringsofinstagram': 1, 'jhumkas': 1, 'jhumkalove': 1,
             'tuesdayshoppingtips': 1, 'makememories': 1, 'gifitngideas': 1, 'mattersoftheheart': 1, 'woodenbox': 1,
             'brasswork': 1, 'heartrules': 1, 'birthdays': 1, 'present': 1, 'allthingsexclusive': 1,
             'thinkglobalshoplocal': 1, 'shopoholics': 1, 'staysunsafe': 1, 'scarffashion': 1, '2019': 1, '2k19': 1,
             'Hello2019': 1, '2018': 1, 'HelloFromTheOtherSide': 1, 'NewYearsResolution': 1, 'StartOfSomethingNew': 1,
             'happycustomers': 1, 'curated': 1, 'celebrateindia': 1, 'celebratesmallbusinesses': 1, 'VeganProducts': 1,
             'vegan': 1, 'AnimalSkinFree': 1, 'NoCrueltyToAnimals': 1, 'SaveAnimals': 1, 'ConfrenceBags': 1,
             'TuesdayTip': 1, 'Flagship': 1, 'MedicinalSoaps': 1, 'Orgnic': 1, 'Honey': 1, 'AloeVera': 1, 'shineon': 1,
             'elegantdesign': 1, 'caps': 1, 'hats': 1, 'stars': 1, 'pubglover': 1, 'rfcap': 1, 'coolcaps': 1,
             'popupshow': 1, 'ensemblebyarj': 1, 'summertrends': 1, 'perfumesale': 1, 'gymandyoga': 1,
             'yogiswholift': 1, 'selflove': 1, 'weighttraining': 1, 'fitchicks': 1, 'yoga': 1, 'progresspic': 1,
             'mentalgains': 1, 'younglivingeo': 1, 'progressnotperfection': 1, 'yogainspiration': 1, 'fitspo': 1,
             'omseany': 1, 'lymedontkillmyvibe': 1, 'spooniestrong': 1, 'healthadvocate': 1, 'butyoudontlooksick': 1,
             'handicapped': 1, 'breakingthestigma': 1, 'defyingtheodds': 1, 'autoimmunedisease': 1, 'abasanas': 1,
             'letsstartyoga': 1, 'chronicpain': 1, 'wordsbyseany': 1, 'spiritualgangster': 1, 'cleanse': 1,
             'yogaclasses': 1, 'happyholi': 1, 'holifever': 1, 'coloursoflife': 1, 'red': 1, 'SlingBags': 1,
             'BagsForWoman': 1, 'WomanAccessories': 1, 'shimmerbag': 1, 'partyslings': 1, 'fashionablefridays': 1,
             'slingfling': 1, 'antiquesilver': 1, 'beautifuldesign': 1, 'mom': 1, 'happydance': 1, 'election2020': 1,
             'exerciseyourrights': 1, 'ChikankariKurtis': 1, 'smalbusinesses': 1, 'cutekidsfashion': 1,
             'clogsforkids': 1, 'cutemoneybag': 1, 'cutenesss': 1, 'kidsshoes': 1, 'kidsstuff': 1,
             'wishingyouwereakidagain': 1, '18carat': 1, '92': 1, 'amazingjewellery': 1, 'wednesdayshopping': 1,
             'empoweringentreprenurs': 1, 'entreprenurship': 1, 'homebasedbusiness': 1, 'inspirational': 1,
             'makeithappen': 1, 'ThursdayThoughts': 1, 'KutchiHandicrafts': 1, 'happyEaster': 1,
             'silverjewellerymaking': 1, 'matapayals': 1, 'oneofakindjewelry': 1, 'exclusivesilver': 1,
             'oxidisedearrings': 1, 'oxidised': 1, 'oxidisedchandbalis': 1, 'loveforsilver': 1,
             'loveforsilverjewellery': 1, '925silver': 1, 'astanasilver': 1, 'instajewelry': 1, 'instatag': 1,
             'istanbaubul': 1, 'silverring': 1, 'artisanmade': 1, 'oxidisedsilver': 1, 'exotic': 1, 'loveit': 1,
             'lovemyjewellery': 1, 'fromturkeywithlove': 1, 'sandringham': 1, 'bayside': 1, 'fashionforward': 1,
             'kidsnightwear': 1, 'bacheloretteparty': 1, 'nightsuit': 1, 'cottonnightwear': 1, 'flannelnightsuit': 1,
             'pajamas': 1, 'sleepshirts': 1, 'shorts': 1, 'couplenightwear': 1, 'loungewear': 1, 'bridemaids': 1,
             'bridesmaidsgifts': 1, 'pjs': 1, 'pajamaparty': 1, 'pajamanight': 1, 'sleepover': 1, 'customised': 1,
             'satinnightwear': 1, 'pyjamakids': 1, 'pyjamakidz': 1, 'bajutidurkanakkanakmurah': 1,
             'bajutidurkanakkanak': 1, 'bajutidurkatun': 1, 'setsedondon': 1, 'pyjama': 1, 'bajutidurmurah': 1,
             'bajutidurbudakmurah': 1, 'happyfathersday': 1, 'sundayvibes': 1, 'forallthesuperdads': 1,
             'amazingdiscounts': 1, 'women': 1, 'designersari': 1, 'sixyards': 1, 'EidMubarak': 1, 'WellnessWednday': 1,
             'thebigsale': 1, 'saleupto50': 1, 'sarisale': 1, 'adimaa': 1, 'kanthasari': 1, 'parsigara': 1,
             'linensaris': 1, 'bandhinisaris': 1, 'lehiriya': 1, 'saristory': 1, 'happyAkshayatritiya': 1,
             'auspiciousOccassion': 1, '18caratgold': 1, 'Breadspreads': 1, 'breadspreads': 1, 'Veeba': 1, 'Sauses': 1,
             'FoodDelivery': 1, 'Mayo': 1, 'FoodDistributors': 1, 'FoodBusinesses': 1, 'BombayBarons': 1,
             'spagettiranch': 1, 'quebeceats': 1, 'qceats': 1, 'eatinqc': 1, 'halfandhalf': 1, 'manger': 1,
             'garlicbread': 1, 'cafeattheatelier': 1, 'homemadespreads': 1, 'loveforfood': 1, 'readytouse': 1,
             'freshlymade': 1, 'fromourkitchen': 1, 'bangalorecafes': 1, 'onolovesfood': 1, 'Health': 1, 'Diet': 1,
             'NewYearResolutions': 1, 'HealthyEating': 1, 'imitationjewellery': 1, 'haircare': 1, 'haircareproducts': 1,
             'antidandruff': 1, 'hairgrowth': 1, 'hairoil': 1, 'henna': 1, 'juttilovers': 1, 'gratitudepost': 1,
             'manyshadesof': 1, 'sapphirering': 1, 'sapphireengagementring': 1, 'whatwomenwant': 1, 'whatwomenlove': 1,
             'skincarefanatic': 1, 'skincarehalalbpom': 1, 'skincareaddictph': 1, 'skincarecikarang': 1,
             'skincareraya': 1, 'skincarepersonalized': 1, 'SkincareHeroes': 1, 'skincarenatasha': 1,
             'SkinCareConsultant': 1, 'skincareconsultationonline': 1, 'skincarebio': 1, 'skincarewanita': 1,
             'skincareformenandwomen': 1, 'skincareroutinemurah': 1, 'skincareponorogo': 1, 'skincarebpomhalal': 1,
             'skincarekulit': 1, 'skincareATX': 1, 'skincarepati': 1, 'skincareselebgram': 1, 'skincareonabudget': 1,
             'skincareobssessed': 1, 'skincareshaklee': 1, 'skincaredokter': 1, 'skincaredaily': 1,
             'skincareblogging': 1, 'skincarecoreana': 1, 'OOTD': 1, 'Comfort': 1, 'firstdayofschool': 1,
             'safebottles': 1, 'ShoppingIsBae': 1, 'contemporaryhues': 1, 'kidsroomdecor': 1, 'alarmclocks': 1,
             'keepgoing': 1, 'exoticjewellery': 1, 'feelroyal': 1, 'statementpiece': 1, 'grace': 1, 'pinkstones': 1,
             'bejewelled': 1, 'pizza': 1, 'foodpopup': 1, 'fleaevent': 1, 'petsindia': 1, 'catsinpune': 1, 'Zumba': 1,
             'Fitness': 1, 'Children': 1, 'ChildrensDay': 1, 'AfterParty': 1, 'Vouchers': 1, 'Mom': 1, 'casual': 1,
             'semi': 1, 'exclusivecollection': 1, 'shortkurtis': 1, 'croptop': 1, 'palazzo': 1, 'womenswear': 1,
             'trendsetterthursdays': 1, 'lit': 1, 'jackets': 1, 'Diy': 1, 'Cookies': 1, 'Cake': 1, 'Baking': 1,
             'BakingLove': 1, 'Chef': 1, 'Sweets': 1, 'Desserts': 1, 'DessertsLove': 1, 'cravings': 1, 'cuckooclock': 1,
             'antiqueclocks': 1, 'everythingunderoneroof': 1, 'lucknowis': 1, 'semistitchedclothing': 1,
             'fridayfestivalshopping': 1, 'happyshopping': 1, 'happyfriendshipday': 1, 'bagswithpurpose': 1,
             'mybagmylife': 1, 'bagsthatfityourlife': 1, 'bagsthatrock': 1, 'bagsofstyle': 1, 'CAshews': 1,
             'Chocolate': 1, 'dryfruitchocolate': 1, 'jhumki': 1, 'smallbusinessowner': 1, 'businessowners': 1,
             'businesswomen': 1, 'businessmen': 1, 'newbusiness': 1, 'businesspassion': 1, 'localbusiness': 1,
             'businesscards': 1, 'shopsmallbusiness': 1, 'businessminded': 1, 'womeninbusiness': 1, 'businessquotes': 1,
             'smallbusinesslove': 1, 'businesscoach': 1, 'homebusiness': 1, 'GaneshChaturti': 1, 'GaneshFestival': 1,
             'LordGanesha': 1, 'Fashion': 1, 'FashionAccessories': 1, 'NaturalStones': 1, 'Beautiful': 1, 'Earrings': 1,
             'SilverJewelleryPune': 1, 'PuneFashion': 1, 'bagsale': 1, 'bagslover': 1, 'bagsaddict': 1,
             'Makarsankrant': 1, 'makarsankrant': 1, 'trihaa': 1, 'naturalfood': 1, 'refinedsugaralternative': 1,
             'refinedsugarsubstitute': 1, 'gifthamper': 1, 'tastyandhealthy': 1, 'saynotorefinedsugar': 1,
             'naturalsugars': 1, 'notrefined': 1, 'sugarcanejaggery': 1, 'kitefestival': 1, 'kiteflying': 1,
             'festivegifting': 1, 'sankrantspecial': 1, 'healthygift': 1, 'thoughtfulgift': 1, 'gur': 1,
             'chemicalfree': 1, 'preservativefree': 1, 'kurtipalazzoset': 1, 'kurtipantset': 1, 'getshopping': 1,
             'sugarfreecookies': 1, 'bakersartgallery': 1, 'sunpragasugar': 1, 'multigrain': 1, 'multigrains': 1,
             'multigraincookies': 1, 'cookies': 1, 'cookieseason': 1, 'cookieshop': 1, 'sugarfree': 1,
             'sugarfreelife': 1, 'sugarfreedessert': 1, 'sugarfreerecipes': 1, 'sugarfreeproducts': 1,
             'pragasugarproducts': 1, 'ashrafchef': 1, 'sushantlok': 1, 'gurugram': 1, 'gurgaon': 1, 'haryana': 1,
             'bestbakeriesingurgao': 1, 'chef': 1, 'cookieschef': 1, 'bakersfield': 1, 'bakers': 1,
             'bakersfieldnails': 1, 'custumize': 1, 'supermart1': 1, 'fabricbags': 1, 'mondayinspiration': 1,
             'puneentrepreneurs': 1, 'thriftingfinds': 1, 'announcement': 1, 'Gujarat': 1, 'kutchibedsheets': 1,
             'gemstone': 1, 'positiveenergy': 1, 'rings': 1, 'colorfulgems': 1, 'positivevibes': 1, 'realgems': 1,
             'jotd': 1, 'leatherdufflebags': 1, 'travelsmart': 1, 'summerVacations2019': 1, 'allAboutstyle': 1,
             'beatingTheHeat': 1, 'bagsandhats': 1, 'summerSwag': 1, 'handbagsforsale': 1, 'handbagaddict': 1,
             'jhumkies': 1, 'jhumkicollection': 1, 'oxidizedearrings': 1, 'oxidisedjhumkas': 1, 'BhaiDooj': 1,
             'bhai': 1, 'Bhaijaan': 1, 'Deepawali': 1, 'Diwali2k18': 1, 'afghanjewelleryinindia': 1,
             'oxidizedjewellery': 1, 'chunkyjewellery': 1, 'jewellerylove': 1, 'Western': 1, 'WomanClothing': 1,
             'mlm': 1, 'affiliatemarketing': 1, 'tool': 1, 'reach': 1, 'bedsheetsingapore': 1, 'lbpackaging': 1,
             'lightbulbpackaging': 1, 'packagingcompany': 1, 'packaginginlagos': 1, 'packaginginnigeria': 1,
             'packaging': 1, 'packagingdesign': 1, 'productpackaging': 1, 'packagingbags': 1, 'beddings': 1,
             'beddingsinlagos': 1, 'duvetcover': 1, 'duvet': 1, 'proudlynigerian': 1, 'buynaijabrands': 1, 'empire': 1,
             'cadar': 1, 'cadarbilik': 1, 'coolcadar': 1, 'cutebedsheet': 1, 'coolbedsheet': 1, 'bedroom': 1,
             'sister': 1, 'unstitchedsuits': 1, 'semiformaloutfit': 1, 'ethnicjackets': 1, 'stole': 1, 'watch': 1,
             'rakhisale': 1, 'supersaturday': 1, 'juttismadewithlove': 1, 'happyindependenceday': 1,
             'proudtobeindian': 1, 'freedomthinkers': 1, 'positivechange': 1, 'instapune': 1, 'payalvshankar': 1,
             'pink': 1, 'chickenkari': 1, 'trendytuesday': 1, 'tuesdaythoughts': 1, 'nofilterneeded': 1,
             'fashionearrings': 1, 'hoopearrings': 1, 'studearrings': 1, 'fashionjewelleryfair': 1, 'earringset': 1,
             'bridalearrings': 1, 'earringsmalaysia': 1, 'earringscollection': 1, 'earringstudio': 1, 'instagirls': 1,
             'indianshoppingdubai': 1, 'onlineshoppingaustralia': 1, 'onlineshoppingdeals': 1,
             'onlineshoppingcanada': 1, 'onlineshoppingsingapore': 1, 'blueearrings': 1, 'chicearrings': 1,
             'colorfulearrings': 1, 'earringswagg': 1, 'beautifulearrings': 1, 'gipsyearrings': 1, 'gypsystyle': 1,
             'bohoearrings': 1, 'bohemianearrings': 1, 'earringstagram': 1, 'summervibes': 1, 'indiansummer': 1,
             'beaththeheat': 1, 'ajrakh': 1, 'mashru': 1, 'brothersisterbond': 1, 'fathersdaygifts': 1, '16june2019': 1,
             'fathersday': 1, 'mensperfumes': 1, 'diaries': 1, 'italianleather': 1, 'perfectgifts': 1, 'fordads': 1,
             'bigValentinesDaySale': 1, 'coolbags': 1, 'bugsbags': 1, 'wheelsbags': 1, 'footballfans': 1,
             'quirkybags': 1, 'CushionCoversOnline': 1, 'Aesthtics': 1, 'Cushion': 1, 'Pillow': 1, 'kidsapparel': 1,
             'recklesskids': 1, 'mumboss': 1, 'kidsofinstagram': 1, 'babyclothes': 1, 'supportsmallbusinessess': 1,
             'babiesofinstagram': 1, 'igbabies': 1, 'supportsmallshops': 1, 'brandreps': 1, 'babyapparel': 1,
             'trendykids': 1, 'wahmlife': 1, 'cutebabies': 1, 'ukfashionkids': 1, 'dressupdaily': 1, 'babyfashion': 1,
             'igkids': 1, 'babyootd': 1, 'streetwear': 1, 'wintercoat': 1, 'mumblogger': 1, 'instamom': 1,
             'supportsmall': 1, 'banarasisilkdressmaterial': 1, 'myracollection': 1, 'dressmaterial': 1,
             'dressmaterialindia': 1, 'dressmaterialsindia': 1, 'dressmaterialsshopping': 1, 'dressmaterialonline': 1,
             'dressmaterialsonline': 1, 'dresses': 1, 'indiandresses': 1, 'indiandress': 1, 'indiandressesonline': 1,
             'indiandressmaterials': 1, 'chenderisilkdressmaterials': 1, 'cottondressmaterials': 1, 'salwar': 1,
             'salwarsuit': 1, 'punjabidress': 1, 'chenderisilkdress': 1, 'partyweardressmaterials': 1,
             'cottonrayondressmaterials': 1, 'banarasisilkdressmaterials': 1, 'banarasidressmaterial': 1,
             'codavailable': 1, 'leatherwallets': 1, 'homefurnishing': 1, 'schoolutilities': 1, 'leatherfashion': 1,
             'leatheraccessories': 1, 'leatherWallet': 1, 'leatherbelt': 1, 'leathercrossbody': 1,
             'leatherlaptopbag': 1, 'Day2': 1, 'MenstrualCups': 1, 'PersonalCareProducts': 1, 'MaternityPads': 1,
             'Hygiene': 1, 'personalcareproductsonline': 1, 'classysunglasses': 1, 'gorgeousshades': 1,
             'sunglassesfashion': 1, 'sunglasseslover': 1, 'sunglasses2019': 1, 'sunglassesaddict': 1,
             'sunglassesready': 1, 'sunglassesswag': 1, 'KnowOurSeller': 1, 'snowflakes': 1, 'frozenblue': 1,
             'indianclutches': 1, 'ethnicstyles': 1, 'traditionalclutches': 1, 'clutcheslover': 1, 'clutchfashion': 1,
             'Handbagscheap': 1, 'HandbagsHeavenHandmade': 1, 'handbagsreplika': 1, 'handbagssuperb': 1,
             'handbagsberquality': 1, 'handbagspodcast': 1, 'handbagswoman': 1, 'handbagsdesign': 1, 'handbagsale': 1,
             'handbagsatnordstroms': 1, 'handbagstomake': 1, 'HandBags': 1, 'handbagset': 1, 'handbagshop': 1,
             'handbagspk': 1, 'handbagsales': 1, 'HandbagsWomen': 1, 'handbagslove': 1, 'handbagsbystylupfashion': 1,
             'handbagsph': 1, 'handbagsupergredmalaysia': 1, 'handbagsbelowRM50': 1, 'handbagsitaly': 1,
             'handbagsinthecity': 1, 'handbagsupera': 1, 'Handbagsshop': 1, 'handbagslover': 1, 'handbagstorage': 1,
             'handbagspanama': 1, 'Jumpsuits': 1, 'Belts': 1, 'Tops': 1, 'extendedsale': 1, 'publicdemand': 1,
             'juttiaddict': 1, 'handcraftedfootwear': 1, 'helpingsmallbusiness': 1, 'CharcoalSoap': 1,
             'AloeveraSoap': 1, 'SaffronSoap': 1, 'AntiPollution': 1, 'Acne': 1, 'Blackheads': 1, 'SmoothSkin': 1,
             'NoWrinkles': 1, 'cute': 1, 'kindergarten': 1, 'HandMadeWithLove': 1, 'RaeezJutties': 1,
             'TheBigJuttieSale': 1, 'HandmadeBeauties': 1, 'NamePlate': 1, 'Online': 1, 'wednesdayfinds': 1,
             'vegetabledyed': 1, 'cotton': 1, 'silkcotton': 1, 'decor': 1, 'bedtime': 1, 'gudiPadwa': 1,
             'empoweringEntrepreneurs': 1, 'weekendsale': 1, 'NeverGiveUp': 1, 'LearnFromMistakes': 1, 'KeepTrying': 1,
             'CustomerOriented': 1, 'StartYourOwnBusiness': 1, 'FridayReads': 1, 'Rakhi': 1, 'RakshaBandan': 1,
             'Tuesday': 1, 'kanthadupatta': 1, 'kanthastitch': 1, 'kanthawork': 1, 'kanthaembroidery': 1,
             'kanthasalwar': 1, 'kanthahandembroidery': 1, 'handblockprinted': 1, 'handblockprintedsuits': 1,
             'silkdupatta': 1, 'silkdupattas': 1, 'silkduppata': 1, 'puresilkdupatta': 1, 'puresilkdupattas': 1,
             'cottonsalwars': 1, 'cottonsuits': 1, 'cottonsalwarsuits': 1, 'cottonsalwar': 1, 'cottonsalwarkameez': 1,
             'kurtacotton': 1, 'cottonkurta': 1, 'cottonkurti': 1, 'punjabisuit': 1, 'saree': 1, 'designerdress': 1,
             'bridalshower': 1, 'scarf': 1, 'amazingOffers': 1, 'inaugaralOffers': 1, 'laptopBag': 1, 'duffleBag': 1,
             'multibrandStore': 1, 'Body': 1, 'BathTime': 1, 'SkinLove': 1, 'gudipadva2019': 1,
             'antiquesilverjewellery': 1, 'banarasisari': 1, 'banaras': 1, 'banarasi': 1, 'banarasiya': 1,
             'banarasdiaries': 1, 'banarasisaree': 1, 'banarasdairies': 1, 'banarasghat': 1, 'travel': 1,
             'Travelgram': 1, 'Travelphotography': 1, 'travelblogger': 1, 'traveler': 1, 'traveling': 1, 'traveller': 1,
             'travelingram': 1, 'travels': 1, 'travellife': 1, 'travelphoto': 1, 'TravelAwesome': 1, 'traveldiaries': 1,
             'indiapictures': 1, 'indianblogger': 1, 'indianstyle': 1, 'indianwriters': 1, 'radiomirchi': 1,
             'rjprateek': 1, 'fridaymusings': 1, 'quotestagram': 1, 'quotesoftheday': 1, 'onedayiwill': 1,
             'woodenphotoframe': 1, 'woodenframe': 1, 'personalisedphotoframe': 1, 'customphotoframe': 1,
             'engravedphotoframe': 1, 'thecustommade': 1, 'giftingitems': 1, 'photoframes': 1, 'heartfeltgifts': 1,
             'grandparent': 1, 'gran': 1, 'personalisedgifts': 1, 'giftsforgrandma': 1, 'lovegran': 1, 'supergran': 1,
             'memories': 1, 'photos': 1, 'great2019': 1, 'thanks': 1, 'mirror': 1, 'rustictimber': 1, 'rusticmirror': 1,
             'wombatframes': 1, 'woodworking': 1, 'wood': 1, 'woodenphotoblocks': 1, 'eidoutfit': 1, 'eidjewellery': 1,
             'eventalert': 1, 'donotmiss': 1, 'show': 1, 'Ensemble': 1, 'puneevents': 1, 'bestshow': 1, 'clearance': 1,
             'Candles': 1, 'SportsWear': 1, '2k18Sale': 1, 'goodnews': 1, 'inaugaraloffer': 1, 'Saris': 1,
             'Embroidery': 1, 'IndianWear': 1, 'WomenClothing': 1, 'FlagshipSore': 1, 'Craftsmen': 1, 'Craftwork': 1,
             'Chikankari': 1, 'supermanfans': 1, 'travelstyle': 1, 'summervacation2019': 1, 'travelaccessories': 1,
             'saffronfacecleanser': 1, 'facecleanser': 1, 'vibrantkutch': 1, 'kutchi': 1, 'ajrakhprints': 1,
             'slingbag': 1, 'botd': 1, 'trendytuesdays': 1, 'celebratingindia': 1, 'earthyfeeling': 1,
             'handicraftsmadewithlove': 1, 'bagshaveattitude': 1, 'quirkyBags': 1, 'carryYourStylewithyou': 1,
             'womensdaygift': 1, 'remotecontroltoys': 1, 'giftsforgeeks': 1, 'starwarsgifts': 1, 'toygifts': 1,
             'giftsforkids': 1, 'stuffgift': 1, 'summergift': 1, 'gadgets': 1, 'giftsforher': 1, 'specialgift': 1,
             'lovedones': 1, 'uniquegifts': 1, 'Unique': 1, 'giftidea': 1, 'starwarstoys': 1, 'stardestroyer': 1,
             'starwarsxwing': 1, 'starwars': 1, 'rc': 1, 'rccars': 1, 'remotecontrol': 1, 'spaceship': 1, 'toy': 1,
             'vintage': 1, 'midcentury': 1, 'collectibles': 1, 'Condiments': 1, 'PinkSalt': 1, 'CoconutSugar': 1,
             'HomeMadeMasalas': 1, 'Masala': 1, 'zari': 1, 'borders': 1, 'goldensari': 1, 'brocade': 1, 'blouse': 1,
             'shopcusphome': 1, 'cusphomespaces': 1, 'hearts': 1, 'springdecor': 1, 'spring18': 1, 'homedecoration': 1,
             'likeforfollow': 1, 'likesforlikes': 1, 'likeforlike': 1, 'instashop': 1, 'delhibased': 1, 'cushions': 1,
             'happyhomes': 1, 'goodhomes': 1, 'homedecorideas': 1, 'instalove': 1, 'quirky': 1, 'cornersofmyhome': 1,
             'homedecorindia': 1, 'mirador': 1, 'quirkydecor': 1, 'interior': 1, 'sofa': 1, 'dogfriendlyhome': 1,
             'lovemyjob': 1, 'Heritage': 1, 'IndianClothing': 1, 'RajasthaniWork': 1, 'OnlineMarketplace': 1,
             'happymothersday': 1, 'JewelBox': 1, 'FashionJwellery': 1, 'DecemberOffer': 1, 'GlassBeads': 1,
             'GlassBeadsNecklace': 1, 'ensembleSummeredition': 1, 'iloveshoes': 1, 'comfortshoes': 1, 'shoesaddict': 1,
             'shoesforsale': 1, 'shoestyle': 1, 'shoesshoesshoes': 1, 'Watches': 1, 'wallClocks': 1, 'ADJewellery': 1,
             'silverJewelleryForDailyUse': 1, 'empowersmallbusinesses': 1, 'westernoutfits': 1, 'womenclothing': 1,
             'Retail': 1, 'Outlet': 1, 'HappyShopping': 1, 'indiantraditionaljewellery': 1, 'revivingtraditions': 1,
             'kundanjewellery': 1, 'paasa': 1, 'maangtikka': 1, 'toering': 1, 'handjewellery': 1,
             'handchainringbracelet': 1, 'handchainbracelet': 1, 'haathphool': 1, 'anklets': 1, 'adjustablebracelet': 1,
             'adjustableindiankadas': 1, 'AmulyamJewels': 1, 'festivejewellery': 1, 'jewelleryshopping': 1,
             'lucknowichikankari': 1, 'chickenkarisuits': 1, 'anarkalidress': 1, 'prideoflucknow': 1,
             'exclusivechickenkari': 1, 'kanishawls': 1, 'kanijamawar': 1, 'pashmina': 1, 'ethicalfashion': 1,
             'sustainablefashion': 1, 'kashmirishawls': 1, 'kashmiristole': 1, 'liveauthentic': 1,
             'madebypeoplenotfactories': 1, 'sustainablelifestyle': 1, 'sareesofinstagram': 1, 'slowfashion': 1,
             'indiainspired': 1, 'iwearhandloom': 1, 'woolenshawls': 1, 'supportwomen': 1, 'sareestory': 1,
             'consciousfashion': 1, 'bohemian': 1, 'jamawarshawl': 1, 'jamawar': 1, 'weavesofindia': 1,
             'indianfashionblogger': 1, 'kaniweave': 1, 'KidsClothing': 1, 'Clothes': 1, 'NewBorns': 1, 'NightWear': 1,
             'Tshirts': 1, 'FlgshipStore': 1, 'PlushBags': 1, 'Plush': 1, 'Puppets': 1, 'FingerPuppets': 1,
             'ladiesfootwear': 1, 'luxurylifestyle': 1, 'ladiesstyle': 1, 'fashiondesigner': 1, 'ladieswear': 1,
             'ladiesfashion': 1, 'louboutin': 1, 'louboutinshoes': 1, 'louboutins': 1, 'classywomen': 1,
             'shinyheels': 1, 'fancyshoes': 1, 'luxurydesign': 1, 'louboutinheels': 1, 'dragoncity': 1, 'saudi': 1,
             'bahrain': 1, 'familyshoppingday': 1, 'shoesgame': 1, 'fashionlover': 1, 'bedsheetsmurahmalaysia': 1,
             'onestopstore': 1, 'vogue': 1, 'homedecore': 1, 'order': 1, 'hurryup': 1, 'grabsoon': 1,
             'GrandAtelierSG': 1, 'GrandAtelier': 1, 'tangssg': 1, 'CNY19': 1, 'bedding': 1, 'bedlinen': 1,
             'bedbath': 1, 'royalbeddings': 1, 'NoExcuses': 1, 'adstudded': 1, 'heartbeat': 1, 'dilkidhadkan': 1,
             'lovestruck': 1, 'cutebracelet': 1, 'designerbracelet': 1, 'braceletlove': 1, 'braceletswag': 1,
             'braceletlover': 1, 'braceletoftheday': 1, 'braceletfantasy': 1, 'JoinUs': 1, 'hustling': 1,
             'comfortablefootwear': 1, 'footfetish': 1, 'juttilover': 1, 'gethydrated': 1, 'bottleholders': 1,
             'summertime': 1, 'Marble': 1, 'StoneProducts': 1, 'Ambience': 1, 'republicdaysale': 1, 'cleanbeauty': 1,
             'RepublicDaySale': 1, 'fashionfollow': 1, 'festivity': 1, 'fashionlovers': 1, 'fashionstore': 1,
             'styleinspo': 1, 'republicday': 1, 'collection': 1, 'buy': 1, 'coins': 1, 'stamps': 1, 'mintageworld': 1,
             '20likes': 1, 'look': 1, 'instafollow': 1, 'iphoneonly': 1, 'instacool': 1, 'instago': 1, 'all_shots': 1,
             'webstagram': 1, 'colorful': 1, 'swag': 1, 'retailers': 1, 'stockclearance': 1, 'kurtiset': 1,
             'unstitchedothing': 1, 'juttisale': 1, 'sterlingsilver': 1, 'melbourne': 1, 'australiafashion': 1,
             'workinprogress': 1, 'crestiveprocess': 1, 'formcontentgallery': 1, 'formcontent': 1,
             'h6contemporaryjewelrygroup': 1, 'h6': 1, 'hungariansix': 1, 'hungarian6': 1, 'fruzsifeketehu': 1,
             'fruzsifekete': 1, 'fruzsifeketejewellery': 1, 'fruzsifeketejewelry': 1, 'jewelrygram': 1,
             'budapestjewelry': 1, 'hungarianjewelryartist': 1, 'hungariandesigner': 1, 'bridaljewelry': 1,
             'contemporaryjewellery': 1, 'contemporaryart': 1, 'timelessclocks': 1, 'galloppinghorse': 1,
             'crystalclock': 1, 'limitedstock': 1, 'perfecthousewarminggift': 1, 'beautifulclocks': 1,
             'giftvouchers': 1, 'giftvouchersavailable': 1, 'valentines': 1, 'sothys': 1, 'simplybeautifulstandish': 1,
             'standish': 1, 'beautysalon': 1, 'wigan': 1, 'coppull': 1, 'chorley': 1, 'aspull': 1, 'yatra': 1,
             'GyFTR': 1, 'GiftVouchers': 1, 'Vacation': 1, 'Weekend': 1, 'Travels': 1, 'happygifting': 1, 'babycast': 1,
             'giftcardsavailable': 1, 'giftcardsareboring': 1, 'giftcardsavailables': 1, 'giftcardsfordayssss': 1,
             'GiftCardSpecials': 1, 'giftcardsrule': 1, '3dbags': 1, 'schoolgoing': 1, 'corporategifts': 1,
             'wroughtiron': 1, 'GiftingIdeas': 1, 'DesignerWear': 1, 'handmadeWithLove': 1, 'shayonaCrafts': 1,
             'homedecorproducts': 1, 'Beauces': 1, 'Homedecorproducts': 1, 'blankcanvas': 1, 'newexperiences': 1,
             'ironmirors': 1, 'inhomesession': 1, 'iran': 1, 'turky': 1, 'mumbaifashionblogger': 1, 'highlights': 1,
             'decorbusiness': 1, 'businessdecor': 1, 'urlice': 1, 'chennaiwedding': 1, 'chennaifoodblogger': 1,
             'chennaimodels': 1, 'chennaifashionblogger': 1, 'worldhomelessday': 1, 'decorworld': 1,
             'cakedecoratingworld': 1, 'worlbusiness': 1, 'worldstar': 1, 'jutis': 1, 'JutiLove': 1, 'influencer': 1,
             'puneri': 1, 'womenforwomen': 1, 'apparel': 1, 'Shoes': 1, 'homelinen': 1, 'stealdeals': 1,
             'confessionsofashopaholic': 1, 'faceofthebrand': 1, 'punebrands': 1, 'theeverygirl': 1,
             'contentcreator': 1, 'socialmediajunkie': 1, 'psluxe': 1, 'payalsscribbles': 1, 'WomenEmpowerment': 1,
             'HappyPeriod': 1, 'HealthyEnvironment': 1, 'comfyfurnishing': 1, 'fabrictrays': 1, 'servingtray': 1,
             'ouneinsta': 1, 'HairMask': 1, 'FaceMask': 1, 'HomeMadeProducts': 1, 'amazingfootwear': 1,
             'EmpoweringWomenInBusinesses': 1, 'jewelleryset': 1, 'handmadejewelleryforsale': 1,
             'unstitchesClothing': 1, 'Swadesh': 1, 'firsttime': 1, 'shoppingextravaganza': 1, 'crossbodybag': 1,
             'womenswallets': 1, 'passportcovers': 1, 'newdesigns': 1, 'travelawesome': 1, 'officebag': 1,
             'juttisforkids': 1, 'ilovejuttis': 1, 'girlsloveshoes': 1, 'juttisforgirls': 1, 'Hydrated': 1,
             'DIsounts': 1, 'NewYearEve': 1, 'KIds': 1, 'beapartofarevolution': 1, 'westernwear': 1, 'kidswear': 1,
             'IndependenceDay': 1, 'FreeShipping': 1, 'Free': 1, 'FridayFun': 1, 'FashionFriday': 1, 'FreebieFriday': 1,
             'jewellerylovers': 1, 'eidwishes': 1, 'sharara': 1, 'palazzosets': 1, 'trendsetters': 1, 'stylewear': 1,
             'upto45': 1, 'sariforallseasons': 1, 'stylestorybyraeez': 1, 'FashionJewelery': 1, 'NewArrivals': 1,
             'keychains': 1, 'giftForSomeoneYouLove': 1, 'LastingMemories': 1, 'cuteKeychains': 1, 'styleStory': 1,
             'stylequotient': 1, 'bluejuttis': 1, 'Rosesoap': 1, 'Skincare': 1, 'turmericsoap': 1, 'Homemade': 1,
             'shea': 1, 'cocobutter': 1, 'soaps': 1, 'moisturizing': 1, 'KidsSoap': 1, 'SkinFriendly': 1,
             'ParabenFree': 1, 'SulphateFree': 1, 'TakeCare': 1, 'lucknawikurtis': 1, 'VCfashionhub': 1,
             'rayonkurtis': 1, 'cottonkurtis': 1, 'kurtisforsale': 1, 'plazzo': 1, 'kurtiwithplazo': 1,
             'fancysarees': 1, 'chikankurti': 1, 'kurtas': 1, 'printedkurti': 1, 'lucknawichikankari': 1,
             'tradtionalfashion': 1, 'traditionalwear': 1, 'Rayonkurtis': 1, 'lucknawifashion': 1, 'stylist': 1,
             'Cottonkurtis': 1, 'Voilkurtis': 1, 'georgettekurtis': 1, 'ojasvilucknawichikankari': 1,
             'onlineethnicwear': 1, 'KashmiriKaftan': 1, 'Shawls': 1, 'fridayfashion': 1, 'styleststement': 1,
             'clutches': 1, 'boxclutches': 1, 'kashmiridressmaterial': 1, 'pashminadressmaterial': 1,
             'pashminadresses': 1, 'kashmiriwork': 1, 'kashmiriworkdressmaterial': 1, 'kashmiriworksalwar': 1,
             'latestCollection': 1, 'trendingcollection': 1, 'dressMaterial': 1, 'cottonDressMaterial': 1,
             'instaoutfits': 1, 'instaclothing': 1, 'instadresses': 1, 'instawear': 1, 'instacollection': 1,
             'kiraak': 1, 'hyderabadfashion': 1, 'instadressmaterials': 1, 'happywomensday': 1, 'womenForwomen': 1,
             'totes': 1, 'slings': 1, 'satchel': 1, 'glares': 1, 'reflectors': 1, 'highquality': 1, 'makeup': 1,
             'makeupproducts': 1, 'reasonableprices': 1, 'pastelsandpearls': 1, 'pastelsandpearlsfamily': 1, 'OPT': 1,
             'partybags': 1, 'bagofcards': 1, 'diamondstar': 1, 'kamakshi': 1, 'pendantsets': 1, 'wintercollection': 1,
             'kidsclothing': 1, 'kidswinterclothes': 1, 'baby': 1, 'child': 1, 'kid': 1, 'HashmeApp': 1, 'fun': 1,
             'instakids': 1, 'empoweringwomeninbusinesses': 1, 'DryFruitsLove': 1, 'Cashews': 1, 'Figs': 1,
             'Customize': 1, 'Gift': 1, 'Hampers': 1, 'vintagecollection': 1, 'relivingchildhoodfantasies': 1,
             'oldisgold': 1, 'punkjewellery': 1, 'Deathjewellery': 1, 'silverring925': 1, 'vintagering': 1,
             'Simplepatternjewllery': 1, 'silverjewelry': 1, 'silverjewels': 1, 'Gothicjewellery': 1,
             'Darkjewellery': 1, 'skullsaccessories': 1, 'skullsring': 1, 'Deathaccessories': 1, 'gothicfashion': 1,
             'SterlingSilver': 1, 'DarkAccessories': 1, 'pendantnecklace': 1, 'highjewellery': 1, 'highjewelry': 1,
             'jewelrydesign': 1, 'saturdayvibes': 1, 'saynotoplastic': 1, 'healthyalternatives': 1, 'lunchboxes': 1,
             'noplasticplease': 1, 'HandmadeBags': 1, 'Pouches': 1, 'SpecsCase': 1, 'Case': 1, 'EarphonePouch': 1,
             'marketing': 1, 'marketingstrategy': 1, 'mindset': 1, 'brand': 1, 'marcapersonal': 1, 'follow_me': 1,
             'followforafollow': 1, 'followtrain': 1, 'follow4like': 1, 'saturdayshopping': 1, 'sunnysaturday': 1,
             'comfortable': 1, 'cooltiffinboxes': 1, 'steeltiffins': 1, 'lunchbox': 1, 'merakisalon': 1,
             'merakisalonnc': 1, 'SoFrosty': 1, 'raleighhairstylist': 1, 'hairofinstagram': 1, 'redkenshadeseq': 1,
             'platinumblonde': 1, 'white': 1, 'whitehair': 1, 'creativityheartpurpose': 1, 'Merakisalon': 1,
             'NailArt': 1, 'Nails': 1, 'GoldFoiling': 1, 'nailsofinstagram': 1, 'NailsOnFleek': 1, 'nailedit': 1,
             'Salon': 1, 'Spa': 1, 'tattooedbymeraki': 1, 'merakiunisexsalon': 1, 'mangalore': 1, 'haircolour': 1,
             'partyready': 1, 'wednesdayhair': 1, 'ocassioncalling': 1, 'attendyourvibe': 1, 'tuesdaytip': 1,
             'spectaclecases': 1, 'homegrown': 1, 'fabric': 1, 'wooden': 1, 'sarishopping': 1, 'sarisaturday': 1,
             'withlove': 1, 'silks': 1, 'satins': 1, 'georgettesaree': 1, 'chiffonsaree': 1, 'velvets': 1, 'tassels': 1,
             'dazzles': 1, 'embroidery': 1, 'celebrate': 1, 'internationalfamiliesday': 1,
             'afamilythatshopstogetherstaystogether': 1, 'summermusings': 1, 'greatbag': 1, 'abagtoupliftyourmood': 1,
             'handbaglove': 1, 'puneinstsgrammers': 1, 'sultrysummershappybags': 1, 'happynavroz': 1, 'celebrating': 1,
             'parsinewyear': 1, 'wheredreamscometrue': 1, 'proudmoment': 1, 'glenmarks': 1,
             'empoweringthosewhoempowerothers': 1, 'sportequipments': 1, 'mueller': 1, 'sportsupport': 1,
             'emquartier': 1, 'shoppingonline': 1, 'training': 1, 'workhard': 1, 'boxingcamp': 1, 'sportcamp': 1,
             'boxingclub': 1, 'boxingclubkyiv': 1, 'boxingkiev': 1, 'boxingkyiv': 1, 'boxingworkout': 1,
             'boxinukraine': 1, 'puncher': 1, 'punching': 1, 'kyivsport': 1, 'boxingcoach': 1, 'boxinggloves': 1,
             'sportgoods': 1, 'sportequipment': 1, 'boxingequipment': 1, 'boxingequipments': 1,
             'sportyaroundtheworld': 1, 'sportyathome': 1, 'finallyinoneplace': 1, 'dadisthebest': 1,
             'alwaysbethankful': 1, 'helpwhereveryoucan': 1, '1gmgoldjewellery': 1, 'gemstonesjewelry': 1,
             'beautifuldesigns': 1, 'dailywearchains': 1, 'sundayspecial': 1, 'upto15': 1, 'ThinkBig': 1, 'Juttis': 1,
             'Antique': 1, 'fashionjewellery': 1, 'fashionjewellerystore': 1, 'fashionjewellerycomua': 1,
             'oxidizedsilver': 1, 'afgani': 1, 'afganijewellery': 1, 'earings': 1, 'earringlovers': 1,
             'earringinstagram': 1, 'earringdesign': 1, 'delhifun': 1, 'tiktok': 1, 'morning': 1, 'artificial': 1,
             'earpiercings': 1, 'dogsofinstagram': 1, 'pearlcollection': 1, 'FridayFashiontips': 1, 'modern': 1,
             'Potlis': 1, 'festiveseason': 1, 'brocades': 1, 'celebritystyles': 1, 'ring': 1, 'statementring': 1,
             'ringswag': 1, 'giftsetforgirls': 1, 'pursesandpouches': 1, 'girlslovepink': 1, 'wednesday': 1,
             'wednesdaymotivation': 1, 'humpday': 1, 'acoustic': 1, 'factory': 1, 'wednedaymotivation': 1,
             'weddingsari': 1, 'velvetsari': 1, 'blacksari': 1, 'fashionfriday': 1, 'ilovesaris': 1, 'toysandgifts': 1,
             'toysandgiftsforchristmas': 1, 'toysandgiftshop': 1, 'maileg': 1, 'mailegworld': 1, 'mouseworld': 1,
             'brotherandsister': 1, 'notsobig': 1, 'tuesdaychillday': 1, 'notsobiglondon': 1, 'puzzles': 1,
             'toystore': 1, 'familybusiness': 1, 'folsomca': 1, 'brainyzootoys': 1, 'ravensburgerpuzzles': 1,
             'indoorpladay': 1, 'spaceflyers': 1, 'handeyecoordination': 1, 'januaryhours': 1, 'newhours': 1,
             'TheHaymarketLBI': 1, 'thehaymarket': 1, 'CreateTraffic': 1, 'MondayMotivation': 1, 'payalscribbles': 1,
             'whenindoubtwhereasari': 1, 'gotapattisaree': 1, 'iloveindia': 1, 'ilovesari': 1, 'indianhandloom': 1,
             'empoweringWomenInBusinesses': 1, 'Storefront': 1, 'Shoponline': 1, 'NoPlastic': 1, 'EcoFriendly': 1,
             'Disposables': 1, 'BioDegradable': 1, 'Plates': 1, 'Picnic': 1, 'Areca': 1, 'EnvironmentalFriendly': 1,
             'handmadebeauties': 1, 'colorsofindia': 1, 'weavewednesday': 1, 'kutchihandicrafts': 1,
             'celebratingindianhandicraft': 1, 'stayshady': 1, 'classylook': 1, 'indianclothing': 1, 'tornadofries': 1,
             'Potato': 1, 'SpiralCutter': 1, 'spiralpotato': 1, 'foodie': 1, 'DIY': 1, 'Fries': 1,
             'indowesterndresses': 1, 'indowesternlook': 1, 'indowesternwear': 1, 'indowesternoutfit': 1,
             'indowesternsuits': 1, 'instagoods': 1, 'indowesterngowns': 1, 'indowesternlehenga': 1,
             'indowesternsuit': 1, 'fashiongram': 1, 'instagoodmyphoto': 1, 'photography': 1, 'fashionweek': 1,
             'instagoodlife': 1, 'retail': 1, 'Westernwear': 1, 'menswear': 1, 'Customisedclothing': 1, 'Nightwear': 1,
             'bottomwear': 1, 'BathPowder': 1, 'Scrub': 1, 'Oils': 1, 'HairOil': 1, 'antiDandruffOil': 1,
             'HerbalOIl': 1, 'heritagedesign': 1, 'ethnicjewelley': 1, 'beautifuldesignerjewellery': 1,
             'papermacheart': 1, 'papermacheofkashmir': 1, 'kashmiricrafts': 1, 'kashmiripapermache': 1,
             'allthingsred': 1, 'redishot': 1, 'ilovered': 1, 'gored': 1, 'abVatanDabayegaButton': 1, 'redFMPune': 1,
             'KashmiriShawls': 1, 'Poncho': 1, 'Wool': 1, 'PureWool': 1, 'WinterWear': 1, 'happygudipadwa': 1,
             'gudipadwa2019': 1, 'chetichand': 1, 'ugadi': 1, 'slingBags': 1, 'Handmde': 1, 'Clutches': 1,
             'ShoppingIsBAE': 1, 'DecembeSale': 1, 'tuesdaytreat': 1, 'partyfrocks': 1, 'prettyfrocks': 1,
             'childrenswear': 1, 'fashionbaby': 1, 'childrenfashion': 1, 'specialoccasion': 1, 'kidsootd': 1,
             'childrenclothes': 1, 'responsiblecitizen': 1, 'LifeOfAnEntrepreneur': 1, 'UpsAndDowns': 1,
             'EmpoweringHomeBasedBusiness': 1, 'Collaboration': 1, 'handmadejutti': 1, 'slingbagsintetis': 1,
             'slingbagsidoarjo': 1, 'slingbagsurabaya': 1, 'slingbagsemarang': 1, 'slingbagsmurah': 1,
             'slingbagseken': 1, 'slingbagsemipremium': 1, 'slingbagsurabayamurah': 1, 'slingbagstradivarius': 1,
             'slingbagsolo': 1, 'slingbagselebgram': 1, 'slingbagsnapshot': 1, 'slingbagsbymurahbgt': 1,
             'slingbagsemipremiummurah': 1, 'slingbagsecond': 1, 'slingbagsph': 1, 'slingbagserbaguna': 1,
             'slingbagsyari': 1, 'slingbagsurabayatermutrah': 1, 'slingbagsalatiga': 1, 'hellokittylover': 1,
             'hellokittymania': 1, 'bingeshopping': 1, 'hellokittystuff': 1, 'fridayvibes': 1, 'hellokittyfans': 1,
             'hellokitty': 1, 'flat10': 1, 'jutties': 1, 'weekend': 1, 'weekendsensation': 1, 'weekendsupersale': 1,
             'happyweekend': 1})
        score = jaccard_counter_similarity(counter1, counter2)
        self.assertTrue(0 <= score <= 1)

    def test_name_similarity(self):
        self.assertTrue(0 <= singleword_similarity(self.pinterest_profile, self.flickr_profile) <= 1)
        self.assertTrue(0 <= singleword_similarity(self.twitter_profile, self.flickr_profile) <= 1)
        self.assertTrue(0 <= singleword_similarity(self.instagram_profile, self.flickr_profile) <= 1)
        self.assertTrue(0 <= singleword_similarity(self.pinterest_profile, self.twitter_profile) <= 1)
        self.assertTrue(0 <= singleword_similarity(self.pinterest_profile, self.instagram_profile) <= 1)
        self.assertTrue(0 <= singleword_similarity(self.twitter_profile, self.instagram_profile) <= 1)

    def test_overlapping_urls(self):
        info1 = {'platform': 'instagram', 'username': 'biscuit_boom',
                 'desc': 'Follow me & be rewarded.Fin.;;www.twitter.com/biscuit_boom'}
        info2 = {'platform': 'twitter', 'username': 'Biscuit_Boom',
                 'desc': 'uniquely and naturally yours.'}
        self.assertEqual(1, desc_overlap_url(info1, info2))
        info1 = {'platform': 'instagram', 'username': 'biscuit_boom',
                 'desc': 'Gvn Dmn;;Implementer of  & be rewarded.Fin.'}
        info2 = {'platform': 'twitter', 'username': 'Biscuit_Boom',
                 'desc': 'We are a quirky and fun event planning compat'}
        self.assertEqual(0, desc_overlap_url(info1, info2))


if __name__ == '__main__':
    unittest.main()
